package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"regexp"
	"strconv"
	"strings"
)

var opcodeRe = regexp.MustCompile(`0x([0-9a-fA-F]+)`)
var wireIdentityRe = regexp.MustCompile(`wire:([0-9a-zA-Z]+)`)
var wireLengthRe = regexp.MustCompile(`len:([0-9]+)`)
var fixedValRe = regexp.MustCompile(`val:([a-zA-Z0-9\"\.\(\)\[\]\{\}]+)`)
var writeMarshal = false
var writeUnmarshal = false

func main() {
	srcFile := os.Getenv("GOFILE")
	if os.Args[1] == "s2c" {
		writeMarshal = true
	} else if os.Args[1] == "c2s" {
		writeUnmarshal = true
	} else {
		panic("bad args")
	}
	extraImportsLines := ""
	for _, extraImport := range os.Args[2:] {
		extraImportsLines += fmt.Sprintf("\"%s\"\n", extraImport)
	}
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, srcFile, nil, parser.ParseComments)
	if err != nil {
		panic(err)
	}
	var outStr = fmt.Sprintf(`
// Code generated by go:generate; DO NOT EDIT.

package %s

import (
	%s
	GwPacket "gw1/server/gwpacket"
)

`, os.Getenv("GOPACKAGE"), extraImportsLines)

	var structDoc = make([]*ast.Comment, 0)

	// Inspect the AST to find struct type declarations
	ast.Inspect(node, func(n ast.Node) bool {
		// Find struct type declarations
		switch t := n.(type) {
		case *ast.GenDecl:
			if t.Doc != nil {
				structDoc = t.Doc.List
			}
		case *ast.TypeSpec:
			if structType, ok := t.Type.(*ast.StructType); ok {
				if len(structDoc) == 0 {
					panic(fmt.Errorf("missing struct doc for %s", t.Name.Name))
				}
				if writeMarshal {
					outStr += WriteMarshalFunction(t.Name.Name, structType, structDoc)
				}
				if writeUnmarshal {
					outStr += WriteUnmarshalFunction(t.Name.Name, structType, structDoc)
				}

				structDoc = make([]*ast.Comment, 0)
			}
		}
		return true
	})
	os.WriteFile(fmt.Sprintf("%s_gen.go", strings.Split(srcFile, ".")[0]), []byte(outStr), 0700)
}

func GetOpcode(structName string, docs []*ast.Comment) int {
	// find opcode from comment on struct
	if len(docs) == 0 {
		panic(fmt.Sprintf("missing comments for struct %s", structName))
	}
	var err error
	opcode := int64(0)
	for _, comment := range docs {
		opcodeMatch := opcodeRe.FindStringSubmatch(comment.Text)
		if len(opcodeMatch) > 1 {
			opcode, err = strconv.ParseInt(opcodeMatch[1], 16, 0)
			if err != nil {
				panic(fmt.Errorf("unable to parse opcode for struct %s: %w", structName, err))
			}
		}
	}
	return int(opcode)
}

func GetWireLength(structType *ast.StructType, fieldName string) (length int, ok bool) {
	for _, field := range structType.Fields.List {
		if field.Names[0].Name != fieldName {
			continue
		}
		if field.Comment == nil {
			continue
		}
		for _, comment := range field.Comment.List {
			match := wireLengthRe.FindStringSubmatch(comment.Text)
			if len(match) > 1 {
				len64, err := strconv.ParseInt(match[1], 10, 0)
				if err != nil {
					ok = false
					return
				}
				length = int(len64)
				ok = true
				return
			}
		}
	}
	ok = false
	return
}

func GetFixedVal(structType *ast.StructType, fieldName string) (val string, ok bool) {
	for _, field := range structType.Fields.List {
		if field.Names[0].Name != fieldName {
			continue
		}
		if field.Comment == nil {
			continue
		}
		for _, comment := range field.Comment.List {
			match := fixedValRe.FindStringSubmatch(comment.Text)
			if len(match) > 1 {
				val = match[1]
				ok = true
				return
			}
		}
	}
	ok = false
	return
}

func WriteUnmarshalFunction(name string, structType *ast.StructType, docs []*ast.Comment) (out string) {
	var fields []FieldDef
	for _, field := range structType.Fields.List {
		fd := FieldDef{
			name:     field.Names[0].Name,
			identity: ExtractCustomIdentity(field),
		}
		fields = append(fields, fd)
	}

	out = fmt.Sprintf("func Unmarshal%s(in *GwPacket.In) (resp %s, err error){\n", name, name)

	opcode := GetOpcode(name, docs)
	out += fmt.Sprintf("if in.Opcode() != 0x%x {\n", opcode)
	out += "err = errors.New(\"bad opcode\")\n"
	out += "return\n"
	out += "}\n"

	for _, fd := range fields {
		switch fd.identity {
		case "bool":
			out += fmt.Sprintf("resp.%s, err = in.Bool()\n", fd.name)
		case "uint8":
			out += fmt.Sprintf("resp.%s, err = in.Uint8()\n", fd.name)
		case "uint16":
			out += fmt.Sprintf("resp.%s, err = in.Uint16()\n", fd.name)
		case "uint32":
			out += fmt.Sprintf("resp.%s, err = in.Uint32()\n", fd.name)
		case "float32":
			out += fmt.Sprintf("resp.%s, err = in.Float32()\n", fd.name)
		case "string":
			out += fmt.Sprintf("resp.%s, err = in.UTF16WithLengthPrefix()\n", fd.name)
		case "VarByte":
			out += fmt.Sprintf("%sLen, err := in.Uint16()\n", fd.name)
			out += "if err != nil {\n"
			out += fmt.Sprintf("err = fmt.Errorf(\"read %s.len: %%w\", err)\n", fd.name)
			out += "return\n"
			out += "}\n"
			out += fmt.Sprintf("resp.%s, err = in.Bytes(%sLen)\n", fd.name, fd.name)
		case "[]byte":
			length, ok := GetWireLength(structType, fd.name)
			if !ok {
				panic("unable to parse WireLength")
			}
			out += fmt.Sprintf("resp.%s, err = in.Bytes(%d)\n", fd.name, length)
		default:
			panic(fmt.Errorf("unhandled identity in unmarshal func '%s' field '%s': %s", name, fd.name, fd.identity))
		}
		out += "if err != nil {\n"
		out += fmt.Sprintf("err = fmt.Errorf(\"read %s: %%w\", err)\n", fd.name)
		out += "return\n"
		out += "}\n"
	}

	out += "return\n"
	out += "}\n"
	return
}

func ExtractCustomIdentity(field *ast.Field) (identity string) {
	comments := field.Comment
	if comments != nil {
		for _, comment := range comments.List {
			match := wireIdentityRe.FindStringSubmatch(comment.Text)
			if len(match) > 1 {
				identity = match[1]
				return
			}
		}
	}
	if len(field.Names) > 1 {
		panic("too many field names")
	}
	fieldType := field.Type
	switch t := fieldType.(type) {
	case *ast.Ident:
		identity = t.Name
	case *ast.ArrayType:
		if _, ok := t.Elt.(*ast.Ident); ok && t.Elt.(*ast.Ident).Name == "byte" {
			identity = "[]byte"
		}
		if _, ok := t.Elt.(*ast.Ident); ok && t.Elt.(*ast.Ident).Name == "uint16" {
			identity = "[]uint16"
		}
	default:
		panic("hi")
	}
	return
}

type FieldDef struct {
	name     string
	identity string
}

func WriteMarshalFunction(name string, structType *ast.StructType, docs []*ast.Comment) (out string) {
	var fields []FieldDef
	for _, field := range structType.Fields.List {
		fd := FieldDef{
			name:     field.Names[0].Name,
			identity: ExtractCustomIdentity(field),
		}
		fields = append(fields, fd)
	}
	// Now we have name:type for each field in the struct.

	out = fmt.Sprintf("func Marshal%s(", name)
	for _, fd := range fields {

		_, isFixedVal := GetFixedVal(structType, fd.name)
		if isFixedVal {
			continue
		}
		reqType := fd.identity
		switch fd.identity {
		case "uint8", "uint16", "uint32":
			reqType = "int"
		}
		out += fmt.Sprintf("%s %s, ", fd.name, reqType)
	}
	out += ") (resp GwPacket.Out) {"

	opcode := GetOpcode(name, docs)
	out += fmt.Sprintf("resp = GwPacket.NewOut(0x%x)\n", opcode)

	for _, fd := range fields {
		valToWrite := fd.name
		fixedVal, isFixedVal := GetFixedVal(structType, fd.name)
		if isFixedVal {
			valToWrite = fixedVal
		}
		switch fd.identity {
		case "bool":
			out += fmt.Sprintf("resp.Bool(%s)\n", valToWrite)
		case "uint8":
			out += fmt.Sprintf("resp.Uint8(%s)\n", valToWrite)
		case "uint16":
			out += fmt.Sprintf("resp.Uint16(%s)\n", valToWrite)
		case "uint32":
			out += fmt.Sprintf("resp.Uint32(%s)\n", valToWrite)
		case "float32":
			out += fmt.Sprintf("resp.Float32(%s)\n", valToWrite)
		case "string":
			out += fmt.Sprintf("resp.UTF16WithLengthPrefix(%s)\n", valToWrite)
		case "VarByte":
			if isFixedVal {
				if fixedVal != "[]byte{}" {
					out += fmt.Sprintf("resp.Uint16(%d)\n", len(valToWrite))
					out += fmt.Sprintf("resp.Bytes(%s)\n", valToWrite)
				}
			} else {
				out += fmt.Sprintf("resp.Uint16(len(%s))\n", valToWrite)
				out += fmt.Sprintf("resp.Bytes(%s)\n", valToWrite)
			}
		case "[]uint16":
			out += fmt.Sprintf("resp.Uint16(len(%s))\n", valToWrite)
			out += fmt.Sprintf("for _, i := range %s {\n", valToWrite)
			out += "resp.Uint16(int(i))\n"
			out += "}\n"
		case "VarUTF16":
			out += fmt.Sprintf("resp.Uint16(len(%s) / 2)\n", valToWrite)
			out += fmt.Sprintf("resp.Bytes(%s)\n", valToWrite)
		case "NestedUint32":
			length, ok := GetWireLength(structType, fd.name)
			if ok {
				out += fmt.Sprintf("if len(%s) != %d {\n", fd.name, length)
				out += fmt.Sprintf("panic(fmt.Errorf(\"length check failed for field '%s' of struct '%s': %%d vs %%d\",  len(%s), %d))\n", fd.name, name, fd.name, length)
				out += "}\n"
			}

			out += fmt.Sprintf("resp.Uint8(len(%s))\n", valToWrite)
			out += fmt.Sprintf("for _, i := range %s {\n", valToWrite)
			out += "resp.Uint32(int(i))\n"
			out += "}\n"
		case "VarUint32":
			length, ok := GetWireLength(structType, fd.name)
			if ok {
				out += fmt.Sprintf("if len(%s) != %d {\n", fd.name, length)
				out += fmt.Sprintf("panic(fmt.Errorf(\"length check failed for field '%s' of struct '%s': %%d vs %%d\",  len(%s), %d))\n", fd.name, name, fd.name, length)
				out += "}\n"
			}

			out += fmt.Sprintf("resp.Uint16(len(%s))\n", valToWrite)
			out += fmt.Sprintf("for _, i := range %s {\n", valToWrite)
			out += "resp.Uint32(int(i))\n"
			out += "}\n"
		case "[]byte":
			if !isFixedVal {
				length, ok := GetWireLength(structType, fd.name)
				if ok {
					out += fmt.Sprintf("if len(%s) != %d {\n", fd.name, length)
					out += fmt.Sprintf("panic(fmt.Errorf(\"length check failed for field '%s' of struct '%s': %%d vs %%d\",  len(%s), %d))\n", fd.name, name, fd.name, length)
					out += "}\n"
				}
			}
			out += fmt.Sprintf("resp.Bytes(%s)\n", valToWrite)
		default:
			panic(fmt.Errorf("unhandled identity in marshal func '%s' field '%s': %s", name, fd.name, fd.identity))
		}
	}
	out += "return\n}\n\n"
	return
}
