// Code generated by go:generate; DO NOT EDIT.

package main

import (
	GwPacket "gw1/server/gwpacket"
)

func MarshalRequestResponse(reqNumber int, responseCode int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x3)
	resp.Uint32(reqNumber)
	resp.Uint16(responseCode)
	return
}
