// Code generated by go:generate; DO NOT EDIT.

package main

import (
	GwPacket "gw1/server/gwpacket"
)

func MarshalRequestResponse(reqNumber int, responseCode int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x3)
	resp.Uint32(reqNumber)
	resp.Uint32(responseCode)
	return
}

func MarshalCharacterSummary(reqNumber int, charUUID []byte, unk1 int, charName string, summaryLen int, summary []byte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x7)
	resp.Uint32(reqNumber)
	resp.Bytes(charUUID)
	resp.Uint32(unk1)
	resp.UTF16WithLengthPrefix(charName)
	resp.Uint16(summaryLen)
	resp.Bytes(summary)
	return
}

func MarshalAccountExtraInfoStart(reqNumber int, unk1 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x14)
	resp.Uint32(reqNumber)
	resp.Uint32(unk1)
	return
}

func MarshalAccountExtraInfo(reqNumber int, territoryCode int, languageCode int, unk1 []byte, unk2 []byte, accountUUID []byte, activeCharUUID []byte, unk3 int, entitlementsLength int, entitlements []byte, eulaByte int, unk4 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x11)
	resp.Uint32(reqNumber)
	resp.Uint32(territoryCode)
	resp.Uint32(languageCode)
	resp.Bytes(unk1)
	resp.Bytes(unk2)
	resp.Bytes(accountUUID)
	resp.Bytes(activeCharUUID)
	resp.Uint32(unk3)
	resp.Uint16(entitlementsLength)
	resp.Bytes(entitlements)
	resp.Uint8(eulaByte)
	resp.Uint32(unk4)
	return
}

func MarshalAccountBinaryInfo(reqNumber int, blockLength int, blockBytes []byte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x16)
	resp.Uint32(reqNumber)
	resp.Uint16(blockLength)
	resp.Bytes(blockBytes)
	return
}

func MarshalServerSeed(xoredRandomBytes []byte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1601)
	resp.Bytes(xoredRandomBytes)
	return
}

func MarshalSessionSaltInfo(salt int, unk1 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1)
	resp.Uint32(salt)
	resp.Uint32(unk1)
	return
}

func MarshalInstanceServerInfo(reqNumber int, worldHash int, mapId int, socketData []byte, playerHash int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x9)
	resp.Uint32(reqNumber)
	resp.Uint32(worldHash)
	resp.Uint32(mapId)
	resp.Bytes(socketData)
	resp.Uint32(playerHash)
	return
}
