// Code generated by go:generate; DO NOT EDIT.

package GameService

import (
	"errors"
	"fmt"

	GwPacket "gw1/server/gwpacket"
)

func UnmarshalCreateCharacterFinish(in *GwPacket.In) (resp CreateCharacterFinish, err error) {
	if in.Opcode() != 0x808a {
		err = errors.New("bad opcode")
		return
	}
	resp.name, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read name: %w", err)
		return
	}
	resp.appearance, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read appearance: %w", err)
		return
	}
	resp.ignore, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read ignore: %w", err)
		return
	}
	return
}
func UnmarshalInstanceLoadRequestPlayers(in *GwPacket.In) (resp InstanceLoadRequestPlayers, err error) {
	if in.Opcode() != 0x808f {
		err = errors.New("bad opcode")
		return
	}
	resp.unk1, err = in.Bytes(16)
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	return
}
func UnmarshalUnknown8091(in *GwPacket.In) (resp Unknown8091, err error) {
	if in.Opcode() != 0x8091 {
		err = errors.New("bad opcode")
		return
	}
	unk1Len, err := in.Uint16()
	if err != nil {
		err = fmt.Errorf("read unk1.len: %w", err)
		return
	}
	resp.unk1, err = in.Bytes(unk1Len)
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	return
}
func UnmarshalVerifyClientConnection(in *GwPacket.In) (resp VerifyClientConnection, err error) {
	if in.Opcode() != 0x500 {
		err = errors.New("bad opcode")
		return
	}
	resp.clientVersion, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read clientVersion: %w", err)
		return
	}
	resp.unk3, err = in.Uint16()
	if err != nil {
		err = fmt.Errorf("read unk3: %w", err)
		return
	}
	resp.unk4, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk4: %w", err)
		return
	}
	resp.worldHash, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read worldHash: %w", err)
		return
	}
	resp.mapId, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read mapId: %w", err)
		return
	}
	resp.playerHash, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read playerHash: %w", err)
		return
	}
	resp.accountUUID, err = in.Bytes(16)
	if err != nil {
		err = fmt.Errorf("read accountUUID: %w", err)
		return
	}
	resp.characterUUID, err = in.Bytes(16)
	if err != nil {
		err = fmt.Errorf("read characterUUID: %w", err)
		return
	}
	resp.unk5, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk5: %w", err)
		return
	}
	resp.unk6, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk6: %w", err)
		return
	}
	return
}
func UnmarshalPingReply(in *GwPacket.In) (resp PingReply, err error) {
	if in.Opcode() != 0x8009 {
		err = errors.New("bad opcode")
		return
	}
	resp.unk1, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	return
}
func UnmarshalDyeEquipment(in *GwPacket.In) (resp DyeEquipment, err error) {
	if in.Opcode() != 0x8083 {
		err = errors.New("bad opcode")
		return
	}
	resp.slot, err = in.Uint8()
	if err != nil {
		err = fmt.Errorf("read slot: %w", err)
		return
	}
	resp.color, err = in.Uint8()
	if err != nil {
		err = fmt.Errorf("read color: %w", err)
		return
	}
	return
}
func UnmarshalUpdateProfessionChoice(in *GwPacket.In) (resp UpdateProfessionChoice, err error) {
	if in.Opcode() != 0x805f {
		err = errors.New("bad opcode")
		return
	}
	resp.isPvE, err = in.Bool()
	if err != nil {
		err = fmt.Errorf("read isPvE: %w", err)
		return
	}
	resp.professionId, err = in.Uint8()
	if err != nil {
		err = fmt.Errorf("read professionId: %w", err)
		return
	}
	return
}
func UnmarshalGpuInformation(in *GwPacket.In) (resp GpuInformation, err error) {
	if in.Opcode() != 0x800a {
		err = errors.New("bad opcode")
		return
	}
	resp.unk1, err = in.Bytes(16)
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	resp.unk2, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	resp.unk3, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk3: %w", err)
		return
	}
	resp.unk4, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk4: %w", err)
		return
	}
	resp.unk5, err = in.Bytes(12)
	if err != nil {
		err = fmt.Errorf("read unk5: %w", err)
		return
	}
	resp.unk6, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk6: %w", err)
		return
	}
	resp.unk7, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk7: %w", err)
		return
	}
	resp.unk8, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk8: %w", err)
		return
	}
	resp.unk9, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk9: %w", err)
		return
	}
	resp.unk10, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk10: %w", err)
		return
	}
	resp.unk11, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk11: %w", err)
		return
	}
	resp.unk12, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk12: %w", err)
		return
	}
	resp.driverName, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read driverName: %w", err)
		return
	}
	resp.driverVersion, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read driverVersion: %w", err)
		return
	}
	return
}
func UnmarshalClientSeed(in *GwPacket.In) (resp ClientSeed, err error) {
	if in.Opcode() != 0x4200 {
		err = errors.New("bad opcode")
		return
	}
	resp.seed, err = in.Bytes(64)
	if err != nil {
		err = fmt.Errorf("read seed: %w", err)
		return
	}
	return
}
func UnmarshalChatMessage(in *GwPacket.In) (resp ChatMessage, err error) {
	if in.Opcode() != 0x8063 {
		err = errors.New("bad opcode")
		return
	}
	resp.agentId, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read agentId: %w", err)
		return
	}
	resp.message, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read message: %w", err)
		return
	}
	return
}
func UnmarshalMoveToPoint(in *GwPacket.In) (resp MoveToPoint, err error) {
	if in.Opcode() != 0x803d {
		err = errors.New("bad opcode")
		return
	}
	resp.x, err = in.Float32()
	if err != nil {
		err = fmt.Errorf("read x: %w", err)
		return
	}
	resp.y, err = in.Float32()
	if err != nil {
		err = fmt.Errorf("read y: %w", err)
		return
	}
	resp.plane, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read plane: %w", err)
		return
	}
	return
}
func UnmarshalRotateAgent(in *GwPacket.In) (resp RotateAgent, err error) {
	if in.Opcode() != 0x803f {
		err = errors.New("bad opcode")
		return
	}
	resp.unk1, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	resp.unk2, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	return
}
func UnmarshalLastPosBeforeMoveCancelled(in *GwPacket.In) (resp LastPosBeforeMoveCancelled, err error) {
	if in.Opcode() != 0x8046 {
		err = errors.New("bad opcode")
		return
	}
	resp.x, err = in.Float32()
	if err != nil {
		err = fmt.Errorf("read x: %w", err)
		return
	}
	resp.y, err = in.Float32()
	if err != nil {
		err = fmt.Errorf("read y: %w", err)
		return
	}
	resp.unk2, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	return
}
func UnmarshalMovementUpdate(in *GwPacket.In) (resp MovementUpdate, err error) {
	if in.Opcode() != 0x803c {
		err = errors.New("bad opcode")
		return
	}
	resp.posX, err = in.Float32()
	if err != nil {
		err = fmt.Errorf("read posX: %w", err)
		return
	}
	resp.posY, err = in.Float32()
	if err != nil {
		err = fmt.Errorf("read posY: %w", err)
		return
	}
	resp.unk1, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	resp.facingX, err = in.Float32()
	if err != nil {
		err = fmt.Errorf("read facingX: %w", err)
		return
	}
	resp.facingY, err = in.Float32()
	if err != nil {
		err = fmt.Errorf("read facingY: %w", err)
		return
	}
	resp.unk2, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	return
}
func UnmarshalUpdateTarget(in *GwPacket.In) (resp UpdateTarget, err error) {
	if in.Opcode() != 0x80c0 {
		err = errors.New("bad opcode")
		return
	}
	resp.targetAgentId, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read targetAgentId: %w", err)
		return
	}
	resp.agentId2, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read agentId2: %w", err)
		return
	}
	return
}
func UnmarshalInteractAgent(in *GwPacket.In) (resp InteractAgent, err error) {
	if in.Opcode() != 0x8038 {
		err = errors.New("bad opcode")
		return
	}
	resp.agentId, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read agentId: %w", err)
		return
	}
	resp.action, err = in.Uint8()
	if err != nil {
		err = fmt.Errorf("read action: %w", err)
		return
	}
	return
}
func UnmarshalCancelInteraction(in *GwPacket.In) (resp CancelInteraction, err error) {
	if in.Opcode() != 0x8027 {
		err = errors.New("bad opcode")
		return
	}
	return
}
func UnmarshalClientPingRequest(in *GwPacket.In) (resp ClientPingRequest, err error) {
	if in.Opcode() != 0x800c {
		err = errors.New("bad opcode")
		return
	}
	return
}
func UnmarshalInstanceLoadRequestSpawnPoint(in *GwPacket.In) (resp InstanceLoadRequestSpawnPoint, err error) {
	if in.Opcode() != 0x8087 {
		err = errors.New("bad opcode")
		return
	}
	return
}
func UnmarshalCreateCharRequestPlayer(in *GwPacket.In) (resp CreateCharRequestPlayer, err error) {
	if in.Opcode() != 0x8088 {
		err = errors.New("bad opcode")
		return
	}
	return
}
func UnmarshalInstanceLoadRequestStart(in *GwPacket.In) (resp InstanceLoadRequestStart, err error) {
	if in.Opcode() != 0x8089 {
		err = errors.New("bad opcode")
		return
	}
	return
}
func UnmarshalClientDisconnect(in *GwPacket.In) (resp ClientDisconnect, err error) {
	if in.Opcode() != 0x8008 {
		err = errors.New("bad opcode")
		return
	}
	return
}
func UnmarshalUnknown8090(in *GwPacket.In) (resp Unknown8090, err error) {
	if in.Opcode() != 0x8090 {
		err = errors.New("bad opcode")
		return
	}
	resp.unk1, err = in.Uint8()
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	resp.unk2, err = in.Uint8()
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	return
}
