package gameservice

var instanceDefinitions = struct {
	Instances map[int]instanceDefinition
	Agents    map[string]agentDefinition
}{
	Instances: map[int]instanceDefinition{
		2: {
			Name:      "DEV Test Arena (1v1)",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x2fed,
		},
		3: {
			Name:      "Test Map",
			Expansion: "core",
			MapFileId: 0x340c6,
		},
		6: {
			Name:      "Wizards Isle",
			Expansion: "core",
			MapFileId: 0x1f22c,
		},
		7: {
			Name:      "Warriors Isle",
			Expansion: "core",
			MapFileId: 0x1f1fc,
		},
		8: {
			Name:      "Hunters Isle",
			Expansion: "core",
			MapFileId: 0x1f208,
		},
		9: {
			Name:      "Wizards Isle",
			Expansion: "core",
			MapFileId: 0x1f22c,
		},
		10: {
			Name:      "Bloodstone Fen",
			Expansion: "prophecies",
			MapFileId: 0x34db,
		},
		11: {
			Name:      "The Wilds",
			Expansion: "prophecies",
			MapFileId: 0x9f5c,
		},
		12: {
			Name:      "Aurora Glade",
			Expansion: "prophecies",
			MapFileId: 0x3331,
		},
		13: {
			Name:      "Diessa Lowlands",
			Expansion: "prophecies",
			MapFileId: 0x3a58,
		},
		14: {
			Name:      "Gates of Kryta",
			Expansion: "prophecies",
			MapFileId: 0x8a33,
		},
		15: {
			Name:      "D'Alessio Seaboard",
			Expansion: "prophecies",
			MapFileId: 0x837f,
		},
		16: {
			Name:      "Divine Coast",
			Expansion: "prophecies",
			MapFileId: 0x8381,
		},
		17: {
			Name:      "Talmark Wilderness",
			Expansion: "prophecies",
			MapFileId: 0x84f7,
		},
		18: {
			Name:      "The Black Curtain",
			Expansion: "prophecies",
			MapFileId: 0x84fd,
		},
		19: {
			Name:      "Sanctum Cay",
			Expansion: "prophecies",
			MapFileId: 0x9160,
		},
		20: {
			Name:      "Droknar's Forge",
			Expansion: "prophecies",
			MapFileId: 0x836a,
		},
		21: {
			Name:      "The Frost Gate",
			Expansion: "prophecies",
			MapFileId: 0x33d1,
		},
		22: {
			Name:      "Ice Caves of Sorrow",
			Expansion: "prophecies",
			MapFileId: 0x2f08,
		},
		23: {
			Name:      "Thunderhead Keep",
			Expansion: "prophecies",
			MapFileId: 0x2d2d,
		},
		24: {
			Name:      "Iron Mines of Moladune",
			Expansion: "prophecies",
			MapFileId: 0xba2c,
		},
		25: {
			Name:      "Borlis Pass",
			Expansion: "prophecies",
			MapFileId: 0x32db,
		},
		26: {
			Name:      "Talus Chute",
			Expansion: "prophecies",
			MapFileId: 0xb5fd,
		},
		28: {
			Name:      "The Great Northern Wall",
			Expansion: "prophecies",
			MapFileId: 0x3600,
		},
		29: {
			Name:      "Fort Ranik",
			Expansion: "prophecies",
			MapFileId: 0x3652,
		},
		30: {
			Name:      "Ruins of Surmia",
			Expansion: "prophecies",
			MapFileId: 0x3653,
		},
		31: {
			Name:      "Xaquang Skyway",
			Expansion: "prophecies",
			MapFileId: 0x265f0,
		},
		32: {
			Name:      "Nolani Academy",
			Expansion: "prophecies",
			MapFileId: 0x3659,
		},
		33: {
			Name:      "Old Ascalon",
			Expansion: "prophecies",
			MapFileId: 0x3a59,
		},
		34: {
			Name:      "The Fissure of Woe",
			Expansion: "prophecies",
			MapFileId: 0xf652,
		},
		35: {
			Name:      "Ember Light Camp",
			Expansion: "prophecies",
			MapFileId: 0xd90b,
		},
		36: {
			Name:      "Grendich Courthouse",
			Expansion: "prophecies",
			MapFileId: 0x3a58,
		},
		37: {
			Name:      "Glints Challenge",
			Expansion: "prophecies",
			MapFileId: 0x252c9,
		},
		38: {
			Name:      "Augury Rock",
			Expansion: "prophecies",
			MapFileId: 0xce65,
		},
		39: {
			Name:      "Sardelac Sanitarium",
			Expansion: "prophecies",
			MapFileId: 0x3a59,
		},
		40: {
			Name:      "Piken Square",
			Expansion: "prophecies",
			MapFileId: 0xc775,
		},
		41: {
			Name:      "Sage Lands",
			Expansion: "prophecies",
			MapFileId: 0x9f63,
		},
		42: {
			Name:      "Mamnoon Lagoon",
			Expansion: "prophecies",
			MapFileId: 0x9f69,
		},
		43: {
			Name:      "Silverwood",
			Expansion: "prophecies",
			MapFileId: 0x9f6c,
		},
		44: {
			Name:      "Ettins Back",
			Expansion: "prophecies",
			MapFileId: 0x9f5e,
		},
		45: {
			Name:      "Reed Bog",
			Expansion: "prophecies",
			MapFileId: 0x9f62,
		},
		46: {
			Name:      "The Falls",
			Expansion: "prophecies",
			MapFileId: 0x9f68,
		},
		47: {
			Name:      "Dry Top",
			Expansion: "prophecies",
			MapFileId: 0x9f61,
		},
		48: {
			Name:      "Tangle Root",
			Expansion: "prophecies",
			MapFileId: 0x9f6b,
		},
		49: {
			Name:      "Henge of Denravi",
			Expansion: "prophecies",
			MapFileId: 0x9f37,
		},
		51: {
			Name:      "Senji's Corner",
			Expansion: "factions",
			MapFileId: 0x265f0,
		},
		52: {
			Name:      "Burning Isle",
			Expansion: "core",
			MapFileId: 0x1f24d,
		},
		53: {
			Name:      "Tears of the Fallen",
			Expansion: "prophecies",
			MapFileId: 0xa0e8,
		},
		54: {
			Name:      "Scoundrels Rise",
			Expansion: "prophecies",
			MapFileId: 0xa0e9,
		},
		55: {
			Name:      "Lion's Arch",
			Expansion: "prophecies",
			MapFileId: 0x34fd,
		},
		56: {
			Name:      "Cursed Lands",
			Expansion: "prophecies",
			MapFileId: 0x85a8,
		},
		57: {
			Name:      "Bergen Hot Springs",
			Expansion: "prophecies",
			MapFileId: 0x85a8,
		},
		58: {
			Name:      "North Kryta Province",
			Expansion: "prophecies",
			MapFileId: 0x4e706,
		},
		59: {
			Name:      "Nebo Terrace",
			Expansion: "prophecies",
			MapFileId: 0x85a8,
		},
		60: {
			Name:      "Majestys Rest",
			Expansion: "prophecies",
			MapFileId: 0x8610,
		},
		61: {
			Name:      "Twin Serpent Lakes",
			Expansion: "prophecies",
			MapFileId: 0x8611,
		},
		62: {
			Name:      "Watchtower Coast",
			Expansion: "prophecies",
			MapFileId: 0x85ae,
		},
		63: {
			Name:      "Stingray Strand",
			Expansion: "prophecies",
			MapFileId: 0x85e9,
		},
		64: {
			Name:      "Kessex Peak",
			Expansion: "prophecies",
			MapFileId: 0x85b1,
		},
		67: {
			Name:      "Burning Isle",
			Expansion: "core",
			MapFileId: 0x1f24d,
		},
		68: {
			Name:      "Frozen Isle",
			Expansion: "core",
			MapFileId: 0x1f265,
		},
		69: {
			Name:      "Nomads Isle",
			Expansion: "core",
			MapFileId: 0x1f268,
		},
		70: {
			Name:      "Druid's Isle",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x1f27a,
		},
		71: {
			Name:      "Isle of the Dead",
			Expansion: "core",
			MapFileId: 0x1f29b,
		},
		72: {
			Name:      "The Underworld",
			Expansion: "prophecies",
			MapFileId: 0xf653,
		},
		73: {
			Name:      "Riverside Province",
			Expansion: "prophecies",
			MapFileId: 0x29ba,
		},
		75: {
			Name:      "The Hall of Heroes",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x36b4,
		},
		77: {
			Name:      "House zu Heltzer",
			Expansion: "factions",
			MapFileId: 0x25e13,
		},
		78: {
			Name:      "The Courtyard",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x36a5,
		},
		80: {
			Name:      "Burial Mounds",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x3bb2,
		},
		81: {
			Name:      "Ascalon City",
			Expansion: "prophecies",
			MapFileId: 0x5624,
		},
		82: {
			Name:      "Tomb of the Primeval Kings",
			Expansion: "prophecies",
			MapFileId: 0x288a0,
		},
		84: {
			Name:      "The Underworld",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x402c,
		},
		87: {
			Name:      "Icedome",
			Expansion: "prophecies",
			MapFileId: 0xb5ff,
		},
		88: {
			Name:      "Iron Horse Mine",
			Expansion: "prophecies",
			MapFileId: 0xb600,
		},
		89: {
			Name:      "Anvil Rock",
			Expansion: "prophecies",
			MapFileId: 0xb601,
		},
		90: {
			Name:      "Lornars Pass",
			Expansion: "prophecies",
			MapFileId: 0xb602,
		},
		91: {
			Name:      "Snake Dance",
			Expansion: "prophecies",
			MapFileId: 0x2fd4,
		},
		92: {
			Name:      "Tascas Demise",
			Expansion: "prophecies",
			MapFileId: 0xb605,
		},
		94: {
			Name:      "Ice Floe",
			Expansion: "prophecies",
			MapFileId: 0xb606,
		},
		95: {
			Name:      "Witmans Folly",
			Expansion: "prophecies",
			MapFileId: 0xb607,
		},
		96: {
			Name:      "Mineral Springs",
			Expansion: "prophecies",
			MapFileId: 0xb608,
		},
		97: {
			Name:      "Dreadnoughts Drift",
			Expansion: "prophecies",
			MapFileId: 0xb609,
		},
		98: {
			Name:      "Frozen Forest",
			Expansion: "prophecies",
			MapFileId: 0xb60a,
		},
		99: {
			Name:      "Travelers Vale",
			Expansion: "prophecies",
			MapFileId: 0xb60b,
		},
		100: {
			Name:      "Deldrimor Bowl",
			Expansion: "prophecies",
			MapFileId: 0xb60c,
		},
		101: {
			Name:      "Regent Valley",
			Expansion: "prophecies",
			MapFileId: 0xc774,
		},
		102: {
			Name:      "The Breach",
			Expansion: "prophecies",
			MapFileId: 0xc775,
		},
		103: {
			Name:      "Ascalon Foothills",
			Expansion: "prophecies",
			MapFileId: 0xc776,
		},
		104: {
			Name:      "Pockmark Flats",
			Expansion: "prophecies",
			MapFileId: 0xc777,
		},
		105: {
			Name:      "Dragons Gullet",
			Expansion: "prophecies",
			MapFileId: 0xc778,
		},
		106: {
			Name:      "Flame Temple Corridor",
			Expansion: "prophecies",
			MapFileId: 0xc778,
		},
		107: {
			Name:      "Eastern Frontier",
			Expansion: "prophecies",
			MapFileId: 0xc77a,
		},
		108: {
			Name:      "The Scar",
			Expansion: "prophecies",
			MapFileId: 0xcbc6,
		},
		109: {
			Name:      "The Amnoon Oasis",
			Expansion: "prophecies",
			MapFileId: 0xceb6,
		},
		110: {
			Name:      "Diviners Ascent",
			Expansion: "prophecies",
			MapFileId: 0xce55,
		},
		111: {
			Name:      "Vulture Drifts",
			Expansion: "prophecies",
			MapFileId: 0xce56,
		},
		112: {
			Name:      "The Arid Sea",
			Expansion: "prophecies",
			MapFileId: 0xce5e,
		},
		113: {
			Name:      "Prophets Path",
			Expansion: "prophecies",
			MapFileId: 0xce63,
		},
		114: {
			Name:      "Salt Flats",
			Expansion: "prophecies",
			MapFileId: 0xce64,
		},
		115: {
			Name:      "Skyward Reach",
			Expansion: "prophecies",
			MapFileId: 0xce65,
		},
		116: {
			Name:      "Dunes of Despair",
			Expansion: "prophecies",
			MapFileId: 0xce66,
		},
		117: {
			Name:      "Thirsty River",
			Expansion: "prophecies",
			MapFileId: 0xce67,
		},
		118: {
			Name:      "Elona Reach",
			Expansion: "prophecies",
			MapFileId: 0xce68,
		},
		119: {
			Name:      "Augury Rock",
			Expansion: "prophecies",
			MapFileId: 0xce65,
		},
		120: {
			Name:      "The Dragons Lair",
			Expansion: "prophecies",
			MapFileId: 0xce6a,
		},
		121: {
			Name:      "Perdition Rock",
			Expansion: "prophecies",
			MapFileId: 0xd90b,
		},
		122: {
			Name:      "Ring Of Fire",
			Expansion: "prophecies",
			MapFileId: 0xd900,
		},
		123: {
			Name:      "Abaddon's Mouth",
			Expansion: "prophecies",
			MapFileId: 0xd907,
		},
		124: {
			Name:      "Hell's Precipice",
			Expansion: "prophecies",
			MapFileId: 0xd908,
		},
		125: {
			Name:      "Titan's Tears",
			Expansion: "prophecies",
			MapFileId: 0xd908,
		},
		126: {
			Name:      "Golden Gates",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0xd941,
		},
		127: {
			Name:      "Scarred Earth",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0xd941,
		},
		128: {
			Name:      "The Eternal Grove",
			Expansion: "factions",
			MapFileId: 0x25e1d,
		},
		129: {
			Name:      "Lutgardis Conservatory",
			Expansion: "factions",
			MapFileId: 0x25bde,
		},
		130: {
			Name:      "Vasburg Armory",
			Expansion: "factions",
			MapFileId: 0x25e1d,
		},
		131: {
			Name:      "Serenity Temple",
			Expansion: "prophecies",
			MapFileId: 0xc777,
		},
		132: {
			Name:      "Ice Tooth Cave",
			Expansion: "prophecies",
			MapFileId: 0xb601,
		},
		133: {
			Name:      "Beacon's Perch",
			Expansion: "prophecies",
			MapFileId: 0xb602,
		},
		134: {
			Name:      "Yak's bend",
			Expansion: "prophecies",
			MapFileId: 0xb60b,
		},
		135: {
			Name:      "Frontier Gate",
			Expansion: "prophecies",
			MapFileId: 0xc77a,
		},
		136: {
			Name:      "Beetletun",
			Expansion: "prophecies",
			MapFileId: 0x85ae,
		},
		137: {
			Name:      "Fisherman's Haven",
			Expansion: "prophecies",
			MapFileId: 0x85e9,
		},
		138: {
			Name:      "Temple of the Ages",
			Expansion: "prophecies",
			MapFileId: 0x84fd,
		},
		139: {
			Name:      "Ventari's Refuge",
			Expansion: "prophecies",
			MapFileId: 0x9f5e,
		},
		140: {
			Name:      "Druid's OVerlook",
			Expansion: "prophecies",
			MapFileId: 0x9f63,
		},
		141: {
			Name:      "Maguuma Stade",
			Expansion: "prophecies",
			MapFileId: 0x9f6b,
		},
		142: {
			Name:      "Quarrel Falls",
			Expansion: "prophecies",
			MapFileId: 0x9f6c,
		},
		144: {
			Name:      "Gyala Hatchery",
			Expansion: "factions",
			MapFileId: 0x25e1f,
		},
		145: {
			Name:      "The Catacombs",
			Expansion: "presearing",
			MapFileId: 0x1c530,
		},
		146: {
			Name:      "Lakeside County",
			Expansion: "presearing",
			MapFileId: 0x1b97d,
		},
		147: {
			Name:      "The Northlands",
			Expansion: "presearing",
			MapFileId: 0x1c539,
		},
		148: {
			Name:        "Pre Ascalon City",
			Expansion:   "presearing",
			MapFileId:   0x1b97d,
			SpawnPoints: [][]float32{{9826, 8077, 0}},
		},
		152: {
			Name:      "Heroes' Audience",
			Expansion: "prophecies",
			MapFileId: 0xce63,
		},
		153: {
			Name:      "Seeker's Passage",
			Expansion: "prophecies",
			MapFileId: 0xce64,
		},
		154: {
			Name:      "Destiny's Gorge",
			Expansion: "prophecies",
			MapFileId: 0xcbc6,
		},
		155: {
			Name:      "Camp Rankor",
			Expansion: "prophecies",
			MapFileId: 0x2fd4,
		},
		156: {
			Name:      "The Granite Citadel",
			Expansion: "prophecies",
			MapFileId: 0xb605,
		},
		157: {
			Name:      "Marhan's Grotto",
			Expansion: "prophecies",
			MapFileId: 0xb606,
		},
		158: {
			Name:      "Port Sledge",
			Expansion: "prophecies",
			MapFileId: 0xb607,
		},
		159: {
			Name:      "Copperhammer Mines",
			Expansion: "prophecies",
			MapFileId: 0xb60a,
		},
		162: {
			Name:      "Regent Valley",
			Expansion: "presearing",
			MapFileId: 0x1bb1d,
		},
		163: {
			Name:        "The Barradin Estate",
			Expansion:   "presearing",
			MapFileId:   0x1ba26,
			SpawnPoints: [][]float32{{-6581, 1468, 0}},
		},
		164: {
			Name:        "Ashford Abbey",
			Expansion:   "presearing",
			MapFileId:   0x1b97d,
			SpawnPoints: [][]float32{{-12667, -7200, 0}},
		},
		165: {
			Name:      "Foible's Fair",
			Expansion: "presearing",
			MapFileId: 0x1bacb,
			Agents: []agentSpawnInfo{
				{Name: "ralena_stormbringer", Level: 2, SpawnPoint: [3]float32{-659, 11180, 0}},
				{Name: "vassar", Level: 2, SpawnPoint: [3]float32{-326, 11072, 0}},
				{Name: "laren_merchant", Level: 2, SpawnPoint: [3]float32{-973, 10754, 0}},
			},
			SpawnPoints: [][]float32{{-473, 9089, 0}},
		},
		166: {
			Name:      "Pre Fort Ranik",
			Expansion: "presearing",
			MapFileId: 0x1bb1d,
			Agents: []agentSpawnInfo{
				{Name: "lord_darrin", Level: 7, SpawnPoint: [3]float32{21647, 12613, 0}},
				{Name: "gram_merchant", Level: 2, SpawnPoint: [3]float32{24562, 10317, 0}},
				{Name: "hatcher_collector", Level: 2, SpawnPoint: [3]float32{24594, 15032}},
				{Name: "ascalon_guard", Level: 2, SpawnPoint: [3]float32{23681, 10442, 0}},
				{Name: "ascalon_guard", Level: 2, SpawnPoint: [3]float32{24286, 14174, 0}},
				{Name: "ascalon_guard", Level: 2, SpawnPoint: [3]float32{22523, 9612, 0}},
				{Name: "ascalon_guard", Level: 2, SpawnPoint: [3]float32{20695, 13021, 0}},
				{Name: "ascalon_guard", Level: 2, SpawnPoint: [3]float32{20695, 10754, 0}},
			},
			SpawnPoints: [][]float32{{22218, 11409, 0}},
		},
		181: {
			Name:      "Shiverpeak Arena",
			Expansion: "prophecies",
			MapFileId: 0xb60b,
		},
		185: {
			Name:      "The Underworld",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x402c,
		},
		186: {
			Name:      "The Underworld",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x402c,
		},
		187: {
			Name:      "The Underworld",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x402c,
		},
		188: {
			Name:      "Random Arenas",
			Expansion: "core",
			MapFileId: 0x284db,
		},
		189: {
			Name:      "Team Arenas",
			Expansion: "core",
			MapFileId: 0x28538,
		},
		191: {
			Name:      "Grenths Footprint",
			Expansion: "prophecies",
			MapFileId: 0x25289,
		},
		193: {
			Name:      "Cavalon",
			Expansion: "factions",
			MapFileId: 0x25e15,
		},
		194: {
			Name:      "Kaineng Center",
			Expansion: "factions",
			MapFileId: 0x265f7,
		},
		195: {
			Name:      "Drazach Thicket",
			Expansion: "factions",
			MapFileId: 0x25b9f,
		},
		196: {
			Name:      "Jaya Bluffs",
			Expansion: "factions",
			MapFileId: 0x26526,
		},
		197: {
			Name:      "Shenzun Tunnels",
			Expansion: "factions",
			MapFileId: 0x265f1,
		},
		198: {
			Name:      "Archipelagos",
			Expansion: "factions",
			MapFileId: 0x25dc3,
		},
		199: {
			Name:      "Maishang Hills",
			Expansion: "factions",
			MapFileId: 0x25d0d,
		},
		200: {
			Name:      "Mount Qinkai",
			Expansion: "factions",
			MapFileId: 0x25dd1,
		},
		201: {
			Name:      "Melandrus Hope",
			Expansion: "factions",
			MapFileId: 0x25bde,
		},
		202: {
			Name:      "Rheas Crater",
			Expansion: "factions",
			MapFileId: 0x25df1,
		},
		203: {
			Name:      "Silent Surf",
			Expansion: "factions",
			MapFileId: 0x25e0e,
		},
		204: {
			Name:      "Unwaking Waters",
			Expansion: "factions",
			MapFileId: 0x25e20,
		},
		205: {
			Name:      "Morostav Trail",
			Expansion: "factions",
			MapFileId: 0x25c0e,
		},
		206: {
			Name:      "Deldrimor War Camp",
			Expansion: "prophecies",
			MapFileId: 0x25289,
		},
		209: {
			Name:      "Mourning Veil Falls",
			Expansion: "factions",
			MapFileId: 0x2663a,
		},
		210: {
			Name:      "Ferndale",
			Expansion: "factions",
			MapFileId: 0x25c34,
		},
		211: {
			Name:      "Pongmei Valley",
			Expansion: "factions",
			MapFileId: 0x25e0f,
		},
		212: {
			Name:      "Monastery Overlook",
			Expansion: "factions",
			MapFileId: 0x26529,
		},
		213: {
			Name:      "Zen Daijun",
			Expansion: "factions",
			MapFileId: 0x264d2,
		},
		214: {
			Name:      "Minister Cho's Estate",
			Expansion: "factions",
			MapFileId: 0x2649b,
		},
		215: {
			Name:      "Vizunah Square",
			Expansion: "factions",
			MapFileId: 0x265f8,
		},
		216: {
			Name:      "Nahpui Quarter",
			Expansion: "factions",
			MapFileId: 0x265f9,
		},
		217: {
			Name:      "Tahnnakai Temple",
			Expansion: "factions",
			MapFileId: 0x265fa,
		},
		218: {
			Name:      "Arborstone",
			Expansion: "factions",
			MapFileId: 0x25e16,
		},
		219: {
			Name:      "Boreas Seabed",
			Expansion: "factions",
			MapFileId: 0x25e17,
		},
		220: {
			Name:      "Sunjiang District",
			Expansion: "factions",
			MapFileId: 0x265fb,
		},
		222: {
			Name:      "The Eternal Grove",
			Expansion: "factions",
			MapFileId: 0x25e1d,
		},
		224: {
			Name:      "Gyala Hatchery",
			Expansion: "factions",
			MapFileId: 0x25e1f,
		},
		225: {
			Name:      "Raisu Palace",
			Expansion: "factions",
			MapFileId: 0x2661c,
		},
		226: {
			Name:      "Imperial Sanctum",
			Expansion: "factions",
			MapFileId: 0x2661d,
		},
		227: {
			Name:      "Unwaking Waters",
			Expansion: "factions",
			MapFileId: 0x25e20,
		},
		230: {
			Name:      "Amatz Basin",
			Expansion: "factions",
			MapFileId: 0x25e24,
		},
		232: {
			Name:      "Shadows Passage",
			Expansion: "factions",
			MapFileId: 0x265f8,
		},
		233: {
			Name:      "Raisu Palace",
			Expansion: "factions",
			MapFileId: 0x2661c,
		},
		234: {
			Name:      "The Aurios Mines",
			Expansion: "factions",
			MapFileId: 0x25e28,
		},
		235: {
			Name:      "Panjiang Peninsula",
			Expansion: "factions",
			MapFileId: 0x2655d,
		},
		236: {
			Name:      "Kinya Province",
			Expansion: "factions",
			MapFileId: 0x26578,
		},
		237: {
			Name:      "Haiju Lagoon",
			Expansion: "factions",
			MapFileId: 0x26597,
		},
		238: {
			Name:      "Sunqua Vale",
			Expansion: "factions",
			MapFileId: 0x2659f,
		},
		239: {
			Name:      "Wajjun Bazaar",
			Expansion: "factions",
			MapFileId: 0x265ef,
		},
		240: {
			Name:      "Bukdek Byway",
			Expansion: "factions",
			MapFileId: 0x4e70b,
		},
		241: {
			Name:      "The Undercity",
			Expansion: "factions",
			MapFileId: 0x265f4,
		},
		242: {
			Name:      "Shing Jea Monastery",
			Expansion: "factions",
			MapFileId: 0x26529,
		},
		243: {
			Name:      "Shing Jea Arena",
			Expansion: "factions",
			MapFileId: 0x2661e,
		},
		244: {
			Name:      "Arborstone",
			Expansion: "factions",
			MapFileId: 0x25e16,
		},
		245: {
			Name:      "Minister Chos Estate",
			Expansion: "factions",
			MapFileId: 0x2649b,
		},
		246: {
			Name:      "Zen Daijun",
			Expansion: "factions",
			MapFileId: 0x264d2,
		},
		247: {
			Name:      "Boreas Seabed",
			Expansion: "factions",
			MapFileId: 0x25e17,
		},
		248: {
			Name:      "Great Temple of Balthazar",
			Expansion: "core",
			MapFileId: 0x287b3,
		},
		249: {
			Name:      "Tsumei Village",
			Expansion: "factions",
			MapFileId: 0x2659f,
		},
		250: {
			Name:      "Seitung Harbor",
			Expansion: "factions",
			MapFileId: 0x26529,
		},
		251: {
			Name:      "Ran Musu Gardens",
			Expansion: "factions",
			MapFileId: 0x26578,
		},
		252: {
			Name:      "Linnok Courtyard",
			Expansion: "factions",
			MapFileId: 0x26529,
		},
		256: {
			Name:      "Gates of Kryta",
			Expansion: "prophecies",
			MapFileId: 0x8a33,
		},
		265: {
			Name:      "Nahpui Quarter",
			Expansion: "factions",
			MapFileId: 0x265f9,
		},
		266: {
			Name:      "Urgozs Warren",
			Expansion: "factions",
			MapFileId: 0x28fb4,
		},
		269: {
			Name:      "Tahnnakai Temple",
			Expansion: "factions",
			MapFileId: 0x265fa,
		},
		272: {
			Name:      "Altrumm Ruins",
			Expansion: "factions",
			MapFileId: 0x25e13,
		},
		273: {
			Name:      "Zos Shrivros Channel",
			Expansion: "factions",
			MapFileId: 0x25e15,
		},
		274: {
			Name:      "Dragon's Throat",
			Expansion: "factions",
			MapFileId: 0x28fb8,
		},
		277: {
			Name:      "Harvest Temple",
			Expansion: "factions",
			MapFileId: 0x25e20,
		},
		278: {
			Name:      "Breaker Hollow",
			Expansion: "factions",
			MapFileId: 0x25dd1,
		},
		279: {
			Name:      "Leviathan Pits",
			Expansion: "factions",
			MapFileId: 0x25e1f,
		},
		280: {
			Name:      "Isle of the Nameless",
			Expansion: "core",
			MapFileId: 0x287b3,
		},
		281: {
			Name:      "Zaishen Challenge",
			Expansion: "core",
			MapFileId: 0x287c2,
		},
		282: {
			Name:      "Zaishen Elite",
			Expansion: "core",
			MapFileId: 0x287d2,
		},
		283: {
			Name:      "Maatu Keep",
			Expansion: "factions",
			MapFileId: 0x25e0f,
		},
		284: {
			Name:      "ZinKu Corridor",
			Expansion: "factions",
			MapFileId: 0x265fa,
		},
		286: {
			Name:      "Brauer Academy",
			Expansion: "factions",
			MapFileId: 0x25b9f,
		},
		287: {
			Name:      "Durheim Archives",
			Expansion: "factions",
			MapFileId: 0x2663a,
		},
		288: {
			Name:      "Bai Paasu Reach",
			Expansion: "factions",
			MapFileId: 0x25d0d,
		},
		289: {
			Name:      "Seafarer's Rest",
			Expansion: "factions",
			MapFileId: 0x25df1,
		},
		290: {
			Name:      "Bejunkan Pier",
			Expansion: "factions",
			MapFileId: 0x265f7,
		},
		291: {
			Name:      "Vizunah Square (Local Quarter)",
			Expansion: "factions",
			MapFileId: 0x265f8,
		},
		292: {
			Name:      "Vizunah Square (Foreign Quarter)",
			Expansion: "factions",
			MapFileId: 0x265f8,
		},
		293: {
			Name:      "Fort Aspenwood (Luxon)",
			Expansion: "factions",
			MapFileId: 0x25e1c,
		},
		294: {
			Name:      "Fort Aspenwood (Kurzick)",
			Expansion: "factions",
			MapFileId: 0x25e1c,
		},
		295: {
			Name:      "The Jade Quarry (Luxon)",
			Expansion: "factions",
			MapFileId: 0x25e1e,
		},
		296: {
			Name:      "The Jade Quarry (Kurzick)",
			Expansion: "factions",
			MapFileId: 0x25e1e,
		},
		297: {
			Name:      "Unwaking Waters (Luxon)",
			Expansion: "factions",
			MapFileId: 0x25e20,
		},
		298: {
			Name:      "Unwaking Waters (Kurzick)",
			Expansion: "factions",
			MapFileId: 0x25e20,
		},
		301: {
			Name:      "Raisu Pavilion",
			Expansion: "factions",
			MapFileId: 0x2661c,
		},
		302: {
			Name:      "Kaineng Docks",
			Expansion: "factions",
			MapFileId: 0x265ef,
		},
		303: {
			Name:      "The Marketplace",
			Expansion: "factions",
			MapFileId: 0x265ef,
		},
		307: {
			Name:      "The Deep",
			Expansion: "factions",
			MapFileId: 0x2e195,
		},
		313: {
			Name:      "Saoshang Trail",
			Expansion: "factions",
			MapFileId: 0x26529,
		},
		318: {
			Name:      "DAlessio Arena",
			Expansion: "prophecies",
			MapFileId: 0x1f1c4,
		},
		319: {
			Name:      "Amnoon Arena",
			Expansion: "prophecies",
			MapFileId: 0xceb6,
		},
		320: {
			Name:      "Fort Koga",
			Expansion: "prophecies",
			MapFileId: 0xe9f6,
		},
		321: {
			Name:      "Heroes Crypt",
			Expansion: "prophecies",
			MapFileId: 0x25a0b,
		},
		322: {
			Name:      "Shiverpeak Arena",
			Expansion: "prophecies",
			MapFileId: 0xb60b,
		},
		330: {
			Name:      "Heroes' Ascent",
			Expansion: "core",
			MapFileId: 0x2879c,
		},
		344: {
			Name:      "The Hall of Heroes",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x36b4,
		},
		345: {
			Name:      "The Courtyard",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x36a5,
		},
		347: {
			Name:      "The Underworld",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x402c,
		},
		348: {
			Name:      "Tanglewood Copse",
			Expansion: "factions",
			MapFileId: 0x25e0f,
		},
		349: {
			Name:      "Saint Anjeka's Shrine",
			Expansion: "factions",
			MapFileId: 0x25c34,
		},
		350: {
			Name:      "Eredon Terrace",
			Expansion: "factions",
			MapFileId: 0x25d0d,
		},
		360: {
			Name:      "Isle Of Meditation",
			Expansion: "core",
			MapFileId: 0x28784,
		},
		361: {
			Name:      "Isle of Weeping Stone",
			Expansion: "core",
			MapFileId: 0x2661f,
		},
		362: {
			Name:      "Isle of Jade",
			Expansion: "core",
			MapFileId: 0x26625,
		},
		363: {
			Name:      "Imperial Isle",
			Expansion: "core",
			MapFileId: 0x28736,
		},
		364: {
			Name:      "Isle of Meditation",
			Expansion: "core",
			MapFileId: 0x28784,
		},
		366: {
			Name:      "Shing Jea Arena",
			Expansion: "factions",
			MapFileId: 0x2661e,
		},
		369: {
			Name:      "Jahai Bluffs",
			Expansion: "nightfall",
			MapFileId: 0x353e3,
		},
		371: {
			Name:      "Marga Coast",
			Expansion: "nightfall",
			MapFileId: 0x33f27,
		},
		373: {
			Name:      "Sunward Marches",
			Expansion: "nightfall",
			MapFileId: 0x33f6c,
		},
		375: {
			Name:      "Barbarous Shore",
			Expansion: "nightfall",
			MapFileId: 0x33ff0,
		},
		376: {
			Name:      "Camp Hojanu",
			Expansion: "nightfall",
			MapFileId: 0x33ff0,
		},
		377: {
			Name:      "Bahdok Caverns",
			Expansion: "nightfall",
			MapFileId: 0x34913,
		},
		379: {
			Name:      "Dejarin Estate",
			Expansion: "nightfall",
			MapFileId: 0x34897,
		},
		380: {
			Name:      "Arkjok Ward",
			Expansion: "nightfall",
			MapFileId: 0x356df,
		},
		382: {
			Name:      "Gandara, the Moon Fortress",
			Expansion: "nightfall",
			MapFileId: 0x34873,
		},
		384: {
			Name:      "The Floodplain of Mahnkelon",
			Expansion: "nightfall",
			MapFileId: 0x34435,
		},
		386: {
			Name:      "Turais Procession",
			Expansion: "nightfall",
			MapFileId: 0x3572d,
		},
		387: {
			Name:      "Sunspear Sanctuary",
			Expansion: "nightfall",
			MapFileId: 0x34c38,
		},
		388: {
			Name:      "Aspenwood Gate (Kurzick)",
			Expansion: "factions",
			MapFileId: 0x25e1c,
		},
		389: {
			Name:      "Aspenwood Gate (Luxon)",
			Expansion: "factions",
			MapFileId: 0x25e1c,
		},
		390: {
			Name:      "Jade Flats (Kurzick)",
			Expansion: "factions",
			MapFileId: 0x25e1e,
		},
		391: {
			Name:      "Jade Flats (Luxon)",
			Expansion: "factions",
			MapFileId: 0x25e1e,
		},
		392: {
			Name:      "Yatendi Canyons",
			Expansion: "nightfall",
			MapFileId: 0x3385e,
		},
		393: {
			Name:      "Chantry of Secrets",
			Expansion: "nightfall",
			MapFileId: 0x3385e,
		},
		394: {
			Name:      "Garden of Seborhin",
			Expansion: "nightfall",
			MapFileId: 0x34a54,
		},
		395: {
			Name:      "Holdings of Chokhin",
			Expansion: "nightfall",
			MapFileId: 0x34f33,
		},
		396: {
			Name:      "Mihanu Township",
			Expansion: "nightfall",
			MapFileId: 0x33883,
		},
		397: {
			Name:      "Vehjin Mines",
			Expansion: "nightfall",
			MapFileId: 0x3503d,
		},
		398: {
			Name:      "Basalt Grotto",
			Expansion: "nightfall",
			MapFileId: 0x33bf5,
		},
		399: {
			Name:      "Forum Highlands",
			Expansion: "nightfall",
			MapFileId: 0x3513b,
		},
		402: {
			Name:      "Resplendent Makuun",
			Expansion: "nightfall",
			MapFileId: 0x33dc4,
		},
		403: {
			Name:      "Honur Hill",
			Expansion: "nightfall",
			MapFileId: 0x33dc4,
		},
		404: {
			Name:      "Wilderness of Bahdza",
			Expansion: "nightfall",
			MapFileId: 0x34b0a,
		},
		406: {
			Name:      "Vehtendi Valley",
			Expansion: "nightfall",
			MapFileId: 0x35363,
		},
		407: {
			Name:      "Yahnur Market",
			Expansion: "nightfall",
			MapFileId: 0x33dd6,
		},
		413: {
			Name:      "The Hidden City of Ahdashim",
			Expansion: "nightfall",
			MapFileId: 0x33e11,
		},
		414: {
			Name:      "The Kodash Bazaar",
			Expansion: "nightfall",
			MapFileId: 0x34c07,
		},
		415: {
			Name:      "Lions Gate",
			Expansion: "prophecies",
			MapFileId: 0x2f9fa,
		},
		416: {
			Name:      "Monastery Overlook",
			Expansion: "factions",
			MapFileId: 0x26529,
		},
		419: {
			Name:      "The Mirror of Lyss",
			Expansion: "nightfall",
			MapFileId: 0x33bdf,
		},
		424: {
			Name:      "Kodonur Crossroads",
			Expansion: "nightfall",
			MapFileId: 0x33e6a,
		},
		425: {
			Name:      "Rilohn Refuge",
			Expansion: "nightfall",
			MapFileId: 0x34435,
		},
		426: {
			Name:      "Pogahn Passage",
			Expansion: "nightfall",
			MapFileId: 0x340df,
		},
		427: {
			Name:      "Moddok Crevice",
			Expansion: "nightfall",
			MapFileId: 0x34913,
		},
		428: {
			Name:      "Tihark Orchard",
			Expansion: "nightfall",
			MapFileId: 0x3513b,
		},
		429: {
			Name:      "Consulate",
			Expansion: "nightfall",
			MapFileId: 0x345cc,
		},
		430: {
			Name:      "Plains of Jarin",
			Expansion: "nightfall",
			MapFileId: 0x4e70d,
		},
		431: {
			Name:      "Sunspear Great Hall",
			Expansion: "nightfall",
			MapFileId: 0x33651,
		},
		433: {
			Name:      "Dzagonur Bastion",
			Expansion: "nightfall",
			MapFileId: 0x33dcc,
		},
		434: {
			Name:      "Dasha Vestibule",
			Expansion: "nightfall",
			MapFileId: 0x33e11,
		},
		435: {
			Name:      "Grand Court of Sebelkeh",
			Expansion: "nightfall",
			MapFileId: 0x33bdf,
		},
		436: {
			Name:      "Command Post",
			Expansion: "nightfall",
			MapFileId: 0x34c38,
		},
		437: {
			Name:      "Jokos Domain",
			Expansion: "nightfall",
			MapFileId: 0x33516,
		},
		438: {
			Name:      "Bone Palace",
			Expansion: "nightfall",
			MapFileId: 0x33516,
		},
		439: {
			Name:      "The Ruptured Heart",
			Expansion: "nightfall",
			MapFileId: 0x33574,
		},
		440: {
			Name:      "The Mouth of Torment",
			Expansion: "nightfall",
			MapFileId: 0x33574,
		},
		441: {
			Name:      "The Shattered Ravines",
			Expansion: "nightfall",
			MapFileId: 0x34ce4,
		},
		442: {
			Name:      "Lair of the Forgotten",
			Expansion: "nightfall",
			MapFileId: 0x33583,
		},
		443: {
			Name:      "Poisoned Outcrops",
			Expansion: "nightfall",
			MapFileId: 0x34cf1,
		},
		444: {
			Name:      "The Sulfurous Wastes",
			Expansion: "nightfall",
			MapFileId: 0x34b79,
		},
		446: {
			Name:      "The Alkali Pan",
			Expansion: "nightfall",
			MapFileId: 0x33594,
		},
		449: {
			Name:        "Kamadan, Jewel of Istan",
			Expansion:   "nightfall",
			MapFileId:   0x345cc,
			SpawnPoints: [][]float32{{-9298, 15969, 0}},
		},
		450: {
			Name:      "Gate of Torment",
			Expansion: "nightfall",
			MapFileId: 0x3452b,
		},
		456: {
			Name:      "Churrhir Fields",
			Expansion: "nightfall",
			MapFileId: 0x3cdc9,
		},
		461: {
			Name:      "The Underworld",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x402c,
		},
		463: {
			Name:      "The Underworld",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x402c,
		},
		468: {
			Name:      "Domain of Fear",
			Expansion: "nightfall",
			MapFileId: 0x35832,
		},
		469: {
			Name:      "Gate of Fear",
			Expansion: "nightfall",
			MapFileId: 0x3452b,
		},
		470: {
			Name:      "Domain of Pain",
			Expansion: "nightfall",
			MapFileId: 0x34bcc,
		},
		473: {
			Name:      "Gate of Secrets",
			Expansion: "nightfall",
			MapFileId: 0x3452b,
		},
		474: {
			Name:      "Gate of Anguish",
			Expansion: "nightfall",
			MapFileId: 0x3452b,
		},
		476: {
			Name:      "Jennurs Horde",
			Expansion: "nightfall",
			MapFileId: 0x33c20,
		},
		477: {
			Name:      "Nundu Bay",
			Expansion: "nightfall",
			MapFileId: 0x33f27,
		},
		478: {
			Name:      "Gate of Desolation",
			Expansion: "nightfall",
			MapFileId: 0x3443c,
		},
		479: {
			Name:      "Champions Dawn",
			Expansion: "nightfall",
			MapFileId: 0x336b4,
		},
		480: {
			Name:      "Ruins of Morah",
			Expansion: "nightfall",
			MapFileId: 0x33594,
		},
		481: {
			Name:      "Fahranur, The First City",
			Expansion: "nightfall",
			MapFileId: 0x34d11,
		},
		482: {
			Name:      "Bjora Marches",
			Expansion: "eotn",
			MapFileId: 0x4706b,
		},
		483: {
			Name:      "Zehlon Reach",
			Expansion: "nightfall",
			MapFileId: 0x34d1f,
		},
		484: {
			Name:      "Lahtenda Bog",
			Expansion: "nightfall",
			MapFileId: 0x34d34,
		},
		485: {
			Name:      "Arbor Bay",
			Expansion: "eotn",
			MapFileId: 0x4621e,
		},
		486: {
			Name:      "Issnur Isles",
			Expansion: "nightfall",
			MapFileId: 0x33727,
		},
		487: {
			Name:      "Beknur Harbor",
			Expansion: "nightfall",
			MapFileId: 0x33727,
		},
		488: {
			Name:      "Mehtani Keys",
			Expansion: "nightfall",
			MapFileId: 0x34d44,
		},
		489: {
			Name:      "Kodlonu Hamlet",
			Expansion: "nightfall",
			MapFileId: 0x3372c,
		},
		491: {
			Name:      "Jokanur Diggings",
			Expansion: "nightfall",
			MapFileId: 0x336bf,
		},
		492: {
			Name:      "Blacktide Den",
			Expansion: "nightfall",
			MapFileId: 0x336c5,
		},
		493: {
			Name:      "Consulate Docks",
			Expansion: "nightfall",
			MapFileId: 0x345cc,
		},
		494: {
			Name:      "Gate of Pain",
			Expansion: "nightfall",
			MapFileId: 0x3452b,
		},
		495: {
			Name:      "Gate of Madness",
			Expansion: "nightfall",
			MapFileId: 0x3452b,
		},
		496: {
			Name:      "Abaddons Gate",
			Expansion: "nightfall",
			MapFileId: 0x34498,
		},
		497: {
			Name:      "Sunspear Arena",
			Expansion: "nightfall",
			MapFileId: 0x34c4c,
		},
		499: {
			Name:      "Ice Cliff Chasms",
			Expansion: "eotn",
			MapFileId: 0x4662b,
		},
		501: {
			Name:      "Riven Earth",
			Expansion: "eotn",
			MapFileId: 0x47051,
		},
		502: {
			Name:      "The Astralarium",
			Expansion: "nightfall",
			MapFileId: 0x336c2,
		},
		513: {
			Name:      "Drakkar Lake",
			Expansion: "eotn",
			MapFileId: 0x46801,
		},
		531: {
			Name:      "Uncharted Isle",
			Expansion: "core",
			MapFileId: 0x33056,
		},
		532: {
			Name:      "Isle of Wurms",
			Expansion: "core",
			MapFileId: 0x3321c,
		},
		537: {
			Name:      "Corrupted Isle",
			Expansion: "core",
			MapFileId: 0x3314e,
		},
		539: {
			Name:      "Corrupted Isle",
			Expansion: "core",
			MapFileId: 0x3314e,
		},
		540: {
			Name:      "Isle of Solitude",
			Expansion: "core",
			MapFileId: 0x334a2,
		},
		543: {
			Name:      "Sun Docks",
			Expansion: "nightfall",
			MapFileId: 0x345cc,
		},
		544: {
			Name:      "Chahbek Village",
			Expansion: "nightfall",
			MapFileId: 0x3cdc9,
		},
		545: {
			Name:      "Remains of Sahlahja",
			Expansion: "nightfall",
			MapFileId: 0x3358c,
		},
		546: {
			Name:      "Jaga Moraine",
			Expansion: "eotn",
			MapFileId: 0x4707f,
		},
		548: {
			Name:      "Norrhart Domains",
			Expansion: "eotn",
			MapFileId: 0x4693f,
		},
		549: {
			Name:      "Hero Battles",
			Expansion: "core",
			MapFileId: 0x3c3ee,
		},
		553: {
			Name:      "Varajar Fells",
			Expansion: "eotn",
			MapFileId: 0x46b50,
		},
		554: {
			Name:      "Dajkah Inlet",
			Expansion: "nightfall",
			MapFileId: 0x33f38,
		},
		558: {
			Name:      "Sparkfly Swamp",
			Expansion: "eotn",
			MapFileId: 0x46305,
		},
		559: {
			Name:      "Gate of the Nightfallen Lands",
			Expansion: "nightfall",
			MapFileId: 0x3452b,
		},
		566: {
			Name:      "Verdant Cascades",
			Expansion: "eotn",
			MapFileId: 0x463ba,
		},
		569: {
			Name:      "Magus Stones",
			Expansion: "eotn",
			MapFileId: 0x46427,
		},
		572: {
			Name:      "Alcazia Tangle",
			Expansion: "eotn",
			MapFileId: 0x46547,
		},
		593: {
			Name:      "Fetid River",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x46d8a,
		},
		598: {
			Name:      "The Antechamber",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x46db8,
		},
		600: {
			Name:      "The Hall of Heroes",
			Expansion: "core",
			IsPvp:     true,
			MapFileId: 0x36b4,
		},
		607: {
			Name:      "Heart of the Shiverpeaks",
			Expansion: "eotn",
			MapFileId: 0x474fa,
		},
		624: {
			Name:      "Vloxs Falls",
			Expansion: "eotn",
			MapFileId: 0x4621e,
		},
		625: {
			Name:      "Battledepths",
			Expansion: "eotn",
			MapFileId: 0x475cc,
		},
		638: {
			Name:      "Gadds Encampment",
			Expansion: "eotn",
			MapFileId: 0x46305,
		},
		639: {
			Name:      "Umbral Grotto",
			Expansion: "eotn",
			MapFileId: 0x463ba,
		},
		640: {
			Name:      "Rata Sum",
			Expansion: "eotn",
			MapFileId: 0x46427,
		},
		641: {
			Name:      "Tarnished Haven",
			Expansion: "eotn",
			MapFileId: 0x46547,
		},
		642: {
			Name:      "Eye of the North",
			Expansion: "eotn",
			MapFileId: 0x4662b,
		},
		643: {
			Name:      "Sifhalla",
			Expansion: "eotn",
			MapFileId: 0x46801,
		},
		644: {
			Name:      "Gunnars Hold",
			Expansion: "eotn",
			MapFileId: 0x4693f,
		},
		645: {
			Name:      "Olafstead",
			Expansion: "eotn",
			MapFileId: 0x46b50,
		},
		646: {
			Name:      "Hall of Monuments",
			Expansion: "eotn",
			MapFileId: 0x4662b,
		},
		647: {
			Name:      "Dalada Uplands",
			Expansion: "eotn",
			MapFileId: 0x46ca8,
		},
		648: {
			Name:      "Doomlore Shrine",
			Expansion: "eotn",
			MapFileId: 0x46ca8,
		},
		649: {
			Name:      "Grothmar Wardowns",
			Expansion: "eotn",
			MapFileId: 0x46d85,
		},
		650: {
			Name:      "Longeyes Ledge",
			Expansion: "eotn",
			MapFileId: 0x46d85,
		},
		651: {
			Name:      "Sacnoth Valley",
			Expansion: "eotn",
			MapFileId: 0x47144,
		},
		652: {
			Name:      "Central Transfer Chamber",
			Expansion: "eotn",
			MapFileId: 0x46d86,
		},
		673: {
			Name:      "A Time for Heroes",
			Expansion: "eotn",
			MapFileId: 0x4f717,
		},
		675: {
			Name:      "Boreal Station",
			Expansion: "eotn",
			MapFileId: 0x4662b,
		},
		682: {
			Name:      "Cinematic Eye Vision A",
			Expansion: "eotn",
			MapFileId: 0x4f71c,
		},
		683: {
			Name:      "Cinematic Eye Vision B",
			Expansion: "eotn",
			MapFileId: 0x4f71c,
		},
		684: {
			Name:      "Cinematic Eye Vision C",
			Expansion: "eotn",
			MapFileId: 0x4f71c,
		},
		685: {
			Name:      "Cinematic Eye Vision D",
			Expansion: "eotn",
			MapFileId: 0x4f71c,
		},
		691: {
			Name:      "Beneath Lions Arch",
			Expansion: "eotn",
			MapFileId: 0x47566,
		},
		692: {
			Name:      "Tunnels Below Cantha",
			Expansion: "eotn",
			MapFileId: 0x47566,
		},
		693: {
			Name:      "Caverns Below Kamadan",
			Expansion: "eotn",
			MapFileId: 0x47566,
		},
		704: {
			Name:      "Fronis Irontoe's Lair",
			Expansion: "eotn",
			MapFileId: 0x475df,
		},
		726: {
			Name:      "Plains of Jarin",
			Expansion: "nightfall",
			MapFileId: 0x4693f,
		},
	},
	Agents: map[string]agentDefinition{
		"ralena_stormbringer": {
			Name:               "Ralena Stormbringer",
			EncName:            "32f0 8841 9a09 33f7",
			ModelId:            116712,
			AllegianceFlags:    1886151033,
			Speed:              288,
			Profession:         6,
			FileId:             16258,
			UnkPropertiesBytes: "0f5a dbd6 d257 691d",
		},
		"vassar": {
			Name:               "Vassar",
			EncName:            "32cf 93ba fa50 3899",
			ModelId:            116691,
			AllegianceFlags:    1886151033,
			Speed:              288,
			Profession:         5,
			FileId:             16377,
			UnkPropertiesBytes: "0f56 917e ddfa 4ab3",
		},
		"laren_merchant": {
			Name:               "Laren (Merchant)",
			EncName:            "2d9e f878 bdbf 12e7",
			ModelId:            116698,
			AllegianceFlags:    1852796515,
			Speed:              200,
			Profession:         3,
			FileId:             116227,
			UnkPropertiesBytes: "0f67 9ad6 8f16 76f0",
		},
		"lord_darrin": {
			Name:               "Lord Darrin",
			EncName:            "3494 c84e d433 48d7",
			ModelId:            76594,
			AllegianceFlags:    1852796515,
			Speed:              288,
			Profession:         1,
			FileId:             116227,
			UnkPropertiesBytes: "11b6 cb06 984b 23cd",
		},
		"gram_merchant": {
			Name:               "Gram (Merchant)",
			EncName:            "2da7 f0d6 d159 6765",
			ModelId:            116698,
			AllegianceFlags:    1852796515,
			Speed:              200,
			Profession:         3,
			FileId:             116227,
			UnkPropertiesBytes: "0f67 9ad6 8f16 76f0",
		},
		"hatcher_collector": {
			Name:               "Hatcher (Collector)",
			EncName:            "328a e3b9 aa36 2e69",
			ModelId:            116703,
			AllegianceFlags:    1852796515,
			Speed:              200,
			Profession:         3,
			FileId:             116228,
			UnkPropertiesBytes: "0f57 9dcb ed5f 4007",
		},
		"ascalon_guard": {
			Name:               "Ascalon Guard",
			EncName:            "2b5e 9f0f b437 7153",
			ModelId:            116727,
			AllegianceFlags:    1852796515,
			Speed:              250,
			Profession:         1,
			FileId:             141285,
			UnkPropertiesBytes: "0f5d c416 af26 167b",
		},
	},
}
var fogClearDataFactions = []uint32{
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
}

var fogClearDataNightfall = fogClearDataFactions // same dimensions

var fogClearDataPresearing = []uint32{
	0xFF000006,
	0x03FFFFFF,
	0xFF000006,
	0x03FFFFFF,
	0xFF000006,
	0x03FFFFFF,
	0xFF000006,
	0x03FFFFFF,
	0xFF000006,
	0x03FFFFFF,
	0xFF000006,
	0x03FFFFFF,
	0xFF000006,
	0x03FFFFFF,
	0xFF000006,
	0x03FFFFFF,
}

var fogClearDataProphecies = []uint32{
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
	0xFF000012,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0xFFFFFFFF,
	0x0FFFFFFF,
}
