// Code generated by go:generate; DO NOT EDIT.

package GameService

import (
	"fmt"
	"math"

	GwPacket "gw1/server/gwpacket"
)

func MarshalAgentUpdateNPCName(agentId int, encName VarUTF16) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x9a)
	resp.Uint32(agentId)
	resp.Uint16(len(encName) / 2)
	resp.Bytes(encName)
	return
}

func MarshalPingRequest(unk1 int, unk2 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xc)
	resp.Uint16(unk1)
	resp.Uint32(unk2)
	return
}

func MarshalAgentMovementTick(delta int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1e)
	resp.Uint32(delta)
	return
}

func MarshalMoveToPointS2C(agentId int, x float32, y float32, plane int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x29)
	resp.Uint32(agentId)
	resp.Float32(x)
	resp.Float32(y)
	resp.Uint16(plane)
	resp.Uint16(0)
	return
}

func MarshalPvPItemsEnd() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1b)
	return
}

func MarshalCharCreationStart() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x188)
	return
}

func MarshalCharCreationError(errorCode int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x18a)
	resp.Uint32(errorCode)
	return
}

func MarshalUpdateCurrentMapId(mapId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x98)
	resp.Uint16(mapId)
	resp.Uint8(0)
	return
}

func MarshalAgentUpdateVisualEquipment(agentId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x6d)
	resp.Uint32(agentId)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(10)
	resp.Uint32(13)
	resp.Uint32(11)
	resp.Uint32(14)
	resp.Uint32(12)
	resp.Uint32(0)
	resp.Uint32(0)
	return
}

func MarshalAgentUpdateNPCProperties(agentId int, fileId int, primaryProfession int, level int, unk3 VarUTF16) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x55)
	resp.Uint32(agentId)
	resp.Uint32(fileId)
	resp.Uint32(0)
	resp.Uint32(0x64000000)
	resp.Uint32(0)
	resp.Uint32(0x20C)
	resp.Uint8(primaryProfession)
	resp.Uint8(level)
	resp.Uint16(len(unk3) / 2)
	resp.Bytes(unk3)
	return
}

func MarshalAgentUpdateNPCModel(npcId int, modelId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x56)
	resp.Uint32(npcId)
	resp.Uint16(1)
	resp.Uint32(modelId)
	return
}

func MarshalAgentSpawned(agentId int, agentType int, unk1 int, unk2 int, posX float32, posY float32, plane int, facingX float32, facingY float32, speed float32, allegianceFlags int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x20)
	resp.Uint32(agentId)
	resp.Uint32(agentType)
	resp.Uint8(unk1)
	resp.Uint8(unk2)
	resp.Float32(posX)
	resp.Float32(posY)
	resp.Uint16(plane)
	resp.Float32(facingX)
	resp.Float32(facingY)
	resp.Uint8(1)
	resp.Float32(speed)
	resp.Float32(1.0)
	resp.Uint32(0x41400000)
	resp.Uint32(allegianceFlags)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Float32(0.0)
	resp.Float32(0.0)
	resp.Float32(float32(math.Inf(1)))
	resp.Float32(float32(math.Inf(1)))
	resp.Uint16(0)
	resp.Uint32(0)
	resp.Float32(float32(math.Inf(1)))
	resp.Float32(float32(math.Inf(1)))
	resp.Uint16(0)
	return
}

func MarshalInstanceLoadSpawnPoint(mapFileId int, posX float32, posY float32, plane int, isCinematic bool, unk2 []byte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x194)
	resp.Uint32(mapFileId)
	resp.Float32(posX)
	resp.Float32(posY)
	resp.Uint16(plane)
	resp.Uint8(58)
	resp.Bool(isCinematic)
	if len(unk2) != 8 {
		panic(fmt.Errorf("length check failed for field 'unk2' of struct 'InstanceLoadSpawnPoint': %d vs %d", len(unk2), 8))
	}
	resp.Bytes(unk2)
	return
}

func MarshalInstanceManifestDone(unk1 int, unk2 int, unk3 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x196)
	resp.Uint8(unk1)
	resp.Uint16(unk2)
	resp.Uint32(unk3)
	return
}

func MarshalInstanceManifestData(data VarByte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x195)
	resp.Uint16(len(data))
	resp.Bytes(data)
	return
}

func MarshalInstanceManifestPhase(phase int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x197)
	resp.Uint8(phase)
	return
}

func MarshalReadyForMapSpawn() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1aa)
	resp.Uint32(808531509)
	return
}

func MarshalHeroInfo() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x30)
	resp.Uint16(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(1000)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	return
}

func MarshalInstanceLoadInfo(agentId int, mapId int, isExplorable bool, district int, languageCode int, isObserver bool) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x198)
	resp.Uint32(agentId)
	resp.Uint16(mapId)
	resp.Bool(isExplorable)
	resp.Uint32(district)
	resp.Uint8(languageCode)
	resp.Bool(isObserver)
	return
}

func MarshalInstanceLoadPlayerName(name string) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x17c)
	resp.UTF16WithLengthPrefix(name)
	return
}

func MarshalItemSetProfession(unk1 int, profession int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x159)
	resp.Uint32(unk1)
	resp.Uint8(profession)
	return
}

func MarshalAgentUpdateAttributePoints(agentId int, points1 int, points2 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x37)
	resp.Uint32(agentId)
	resp.Uint8(points1)
	resp.Uint8(points2)
	return
}

func MarshalInstancePlayerDataStart() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x185)
	return
}

func MarshalInstancePlayerDataDone() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x189)
	return
}

func MarshalSkillsUnlocked() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xda)
	resp.Uint16(0)
	return
}

func MarshalCartographyDataStart() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x8a)
	resp.Uint32(64)
	resp.Uint32(1280)
	resp.Uint32(73)
	return
}

func MarshalCartographyData(data []byte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x89)
	resp.Bytes(data)
	return
}

func MarshalMapsUnlocked(data []byte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x93)
	resp.Bytes(data)
	return
}

func MarshalQuestsInfo(data VarByte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x4a)
	resp.Uint16(len(data))
	resp.Bytes(data)
	return
}

func MarshalInstanceLoaded() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xf1)
	resp.Uint32(1886151033)
	return
}

func MarshalVanquishProgress(progress int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xf9)
	resp.Uint16(progress)
	return
}

func MarshalAgentCreatePlayer(agentId int, name string) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x58)
	resp.Uint32(1)
	resp.Uint32(agentId)
	resp.Uint32(103153665)
	resp.Uint8(0)
	resp.Uint32(0)
	resp.Uint32(3435973836)
	resp.UTF16WithLengthPrefix(name)
	return
}

func MarshalAgentInitialEffects(agentId int, effects int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xef)
	resp.Uint32(agentId)
	resp.Uint32(effects)
	return
}

func MarshalAgentDisplayCape(agentId int, isShown bool) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x47)
	resp.Uint32(agentId)
	resp.Bool(isShown)
	return
}

func MarshalAgentSetPlayer(agentId int, playerId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x22)
	resp.Uint32(agentId)
	resp.Uint32(playerId)
	return
}

func MarshalPostProcess() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x6a)
	resp.Uint8(0)
	resp.Uint32(0)
	return
}

func MarshalPartyMemberStreamEnd(partyId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1d2)
	resp.Uint16(partyId)
	return
}

func MarshalUpdatePartySize(unk1 int, unk2 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xaf)
	resp.Uint16(unk1)
	resp.Uint8(unk2)
	return
}

func MarshalPartyCreate(partyId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1d1)
	resp.Uint16(partyId)
	return
}

func MarshalPartyPlayerAdd(partyId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1ca)
	resp.Uint16(partyId)
	resp.Uint16(1)
	resp.Uint8(1)
	return
}

func MarshalInstanceLoadFinish() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x18d)
	return
}

func MarshalPartySetDifficulty(isHardMode bool) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1bd)
	resp.Bool(isHardMode)
	return
}

func MarshalPartySearchSeek() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1dd)
	resp.Uint16(0)
	return
}

func MarshalItemStreamCreate(itemStreamId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x143)
	resp.Uint16(itemStreamId)
	resp.Uint8(0)
	return
}

func MarshalItemMovedToLocation(itemStreamId int, itemLocalId int, pageId int, slow int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x13d)
	resp.Uint16(itemStreamId)
	resp.Uint32(itemLocalId)
	resp.Uint16(pageId)
	resp.Uint8(slow)
	return
}

func MarshalActivateWeaponSet(weaponSetId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x147)
	resp.Uint16(weaponSetId)
	resp.Uint8(0)
	return
}

func MarshalItemWeaponSet(weaponSetId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x146)
	resp.Uint16(1)
	resp.Uint8(weaponSetId)
	resp.Uint32(0)
	resp.Uint32(0)
	return
}

func MarshalInventoryCreateBag(itemStreamId int, bagId int, unk1 int, unk2 int, capacity int, unk3 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x13e)
	resp.Uint16(itemStreamId)
	resp.Uint8(bagId)
	resp.Uint8(unk1)
	resp.Uint16(unk2)
	resp.Uint8(capacity)
	resp.Uint32(unk3)
	return
}

func MarshalItemGeneralInfo(itemLocalId int, fileId int, itemType int, unk1 int, dyeColor int, materials int, unk2 int, itemFlags int, merchantPrice int, itemId int, quantity int, encName VarUTF16, unk4 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x160)
	resp.Uint32(itemLocalId)
	resp.Uint32(fileId)
	resp.Uint8(itemType)
	resp.Uint8(unk1)
	resp.Uint16(dyeColor)
	resp.Uint16(materials)
	resp.Uint8(unk2)
	resp.Uint32(itemFlags)
	resp.Uint32(merchantPrice)
	resp.Uint32(itemId)
	resp.Uint32(quantity)
	resp.Uint16(len(encName) / 2)
	resp.Bytes(encName)
	resp.Uint8(1)
	resp.Uint32(unk4)
	return
}

func MarshalPlayerUnlockedProfessions(agentId int, unlocked int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xb5)
	resp.Uint32(agentId)
	resp.Uint32(unlocked)
	return
}

func MarshalSkillbarUpdate(agentId int, unk1 VarUint32, unk2 VarUint32) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xd9)
	resp.Uint32(agentId)
	if len(unk1) != 8 {
		panic(fmt.Errorf("length check failed for field 'unk1' of struct 'SkillbarUpdate': %d vs %d", len(unk1), 8))
	}
	resp.Uint16(len(unk1))
	for _, i := range unk1 {
		resp.Uint32(i)
	}
	if len(unk2) != 8 {
		panic(fmt.Errorf("length check failed for field 'unk2' of struct 'SkillbarUpdate': %d vs %d", len(unk2), 8))
	}
	resp.Uint16(len(unk2))
	for _, i := range unk2 {
		resp.Uint32(i)
	}
	resp.Uint8(1)
	return
}

func MarshalAgentAttrUpdateInt(attributeId int, agentId int, val int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x9e)
	resp.Uint32(attributeId)
	resp.Uint32(agentId)
	resp.Uint32(val)
	return
}

func MarshalAgentAttrUpdateFloat(attributeId int, agentId int, val float32) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xa1)
	resp.Uint32(attributeId)
	resp.Uint32(agentId)
	resp.Float32(val)
	return
}

func MarshalPlayerAttrSet(xp int, level int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xe8)
	resp.Uint32(xp)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(level)
	resp.Uint32(100)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	resp.Uint32(0)
	return
}

func MarshalPlayerUpdateProfession(agentId int, primaryProfessionId int, secondaryProfessionId int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0xb6)
	resp.Uint32(agentId)
	resp.Uint8(primaryProfessionId)
	resp.Uint8(secondaryProfessionId)
	resp.Uint8(0)
	return
}

func MarshalInstanceLoadHead() (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x17b)
	resp.Uint8(2)
	resp.Uint8(0)
	resp.Uint8(0)
	resp.Uint8(0)
	return
}

func MarshalChatMessageServer(color int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x5d)
	resp.Uint16(0)
	resp.Uint8(color)
	return
}
