// Code generated by go:generate; DO NOT EDIT.

package AuthService

import (
	"errors"
	"fmt"

	GwPacket "gw1/server/gwpacket"
)

func UnmarshalSetActiveCharacter(in *GwPacket.In) (resp SetActiveCharacter, err error) {
	if in.Opcode() != 0x800a {
		err = errors.New("bad opcode")
		return
	}
	resp.reqNumber, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read reqNumber: %w", err)
		return
	}
	resp.charName, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read charName: %w", err)
		return
	}
	return
}
func UnmarshalLoginCharacter(in *GwPacket.In) (resp LoginCharacter, err error) {
	if in.Opcode() != 0x8029 {
		err = errors.New("bad opcode")
		return
	}
	resp.reqNumber, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read reqNumber: %w", err)
		return
	}
	resp.unk1, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	resp.mapId, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read mapId: %w", err)
		return
	}
	resp.unk2, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	resp.unk3, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk3: %w", err)
		return
	}
	resp.unk4, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk4: %w", err)
		return
	}
	return
}
func UnmarshalAddAccessKey(in *GwPacket.In) (resp AddAccessKey, err error) {
	if in.Opcode() != 0x801c {
		err = errors.New("bad opcode")
		return
	}
	resp.reqNumber, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read reqNumber: %w", err)
		return
	}
	resp.key, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read key: %w", err)
		return
	}
	return
}
func UnmarshalClientHashInfo(in *GwPacket.In) (resp ClientHashInfo, err error) {
	if in.Opcode() != 0x2 {
		err = errors.New("bad opcode")
		return
	}
	resp.clientVersion, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read clientVersion: %w", err)
		return
	}
	resp.unkHash, err = in.Bytes(16)
	if err != nil {
		err = fmt.Errorf("read unkHash: %w", err)
		return
	}
	return
}
func UnmarshalClientVersionInfo(in *GwPacket.In) (resp ClientVersionInfo, err error) {
	if in.Opcode() != 0x400 {
		err = errors.New("bad opcode")
		return
	}
	resp.length, err = in.Uint16()
	if err != nil {
		err = fmt.Errorf("read length: %w", err)
		return
	}
	resp.clientVersion, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read clientVersion: %w", err)
		return
	}
	resp.unk2, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	resp.unk3, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk3: %w", err)
		return
	}
	return
}
func UnmarshalUnknown8000(in *GwPacket.In) (resp Unknown8000, err error) {
	if in.Opcode() != 0x0 {
		err = errors.New("bad opcode")
		return
	}
	resp.unk1, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	return
}
func UnmarshalComputerInfo(in *GwPacket.In) (resp ComputerInfo, err error) {
	if in.Opcode() != 0x1 {
		err = errors.New("bad opcode")
		return
	}
	resp.userName, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read userName: %w", err)
		return
	}
	resp.computerName, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read computerName: %w", err)
		return
	}
	return
}
func UnmarshalUnknown8023(in *GwPacket.In) (resp Unknown8023, err error) {
	if in.Opcode() != 0x23 {
		err = errors.New("bad opcode")
		return
	}
	resp.unk1, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	return
}
func UnmarshalGetAccountInfo(in *GwPacket.In) (resp GetAccountInfo, err error) {
	if in.Opcode() != 0x8038 {
		err = errors.New("bad opcode")
		return
	}
	resp.reqNumber, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read reqNumber: %w", err)
		return
	}
	resp.uuid1, err = in.Bytes(16)
	if err != nil {
		err = fmt.Errorf("read uuid1: %w", err)
		return
	}
	resp.gameTokenFromPortalService, err = in.Bytes(16)
	if err != nil {
		err = fmt.Errorf("read gameTokenFromPortalService: %w", err)
		return
	}
	resp.unk1, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	return
}
func UnmarshalAskServerResponse(in *GwPacket.In) (resp AskServerResponse, err error) {
	if in.Opcode() != 0x8035 {
		err = errors.New("bad opcode")
		return
	}
	resp.reqNumber, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read reqNumber: %w", err)
		return
	}
	return
}
func UnmarshalLanguageInfo(in *GwPacket.In) (resp LanguageInfo, err error) {
	if in.Opcode() != 0x8016 {
		err = errors.New("bad opcode")
		return
	}
	resp.languageCode, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read languageCode: %w", err)
		return
	}
	return
}
func UnmarshalDisconnect(in *GwPacket.In) (resp Disconnect, err error) {
	if in.Opcode() != 0x800d {
		err = errors.New("bad opcode")
		return
	}
	resp.errorCode, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read errorCode: %w", err)
		return
	}
	return
}
func UnmarshalSetPlayerOnlineVisibilityStatus(in *GwPacket.In) (resp SetPlayerOnlineVisibilityStatus, err error) {
	if in.Opcode() != 0x800e {
		err = errors.New("bad opcode")
		return
	}
	resp.visibility, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read visibility: %w", err)
		return
	}
	return
}
func UnmarshalClientSeed(in *GwPacket.In) (resp ClientSeed, err error) {
	if in.Opcode() != 0x4200 {
		err = errors.New("bad opcode")
		return
	}
	resp.seedBytes, err = in.Bytes(64)
	if err != nil {
		err = fmt.Errorf("read seedBytes: %w", err)
		return
	}
	return
}
func UnmarshalUpdateSettingsLength(in *GwPacket.In) (resp UpdateSettingsLength, err error) {
	if in.Opcode() != 0x8021 {
		err = errors.New("bad opcode")
		return
	}
	resp.reqNumber, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read reqNumber: %w", err)
		return
	}
	resp.unk2, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	return
}
func UnmarshalUpdateSettings(in *GwPacket.In) (resp UpdateSettings, err error) {
	if in.Opcode() != 0x8020 {
		err = errors.New("bad opcode")
		return
	}
	resp.unk1, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	settingsLen, err := in.Uint16()
	if err != nil {
		err = fmt.Errorf("read settings.len: %w", err)
		return
	}
	resp.settings, err = in.Bytes(settingsLen)
	if err != nil {
		err = fmt.Errorf("read settings: %w", err)
		return
	}
	return
}
func UnmarshalDeleteCharacter(in *GwPacket.In) (resp DeleteCharacter, err error) {
	if in.Opcode() != 0x8007 {
		err = errors.New("bad opcode")
		return
	}
	resp.reqNumber, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read reqNumber: %w", err)
		return
	}
	resp.name, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read name: %w", err)
		return
	}
	return
}
func UnmarshalUnknown8009(in *GwPacket.In) (resp Unknown8009, err error) {
	if in.Opcode() != 0x8009 {
		err = errors.New("bad opcode")
		return
	}
	resp.reqNumber, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read reqNumber: %w", err)
		return
	}
	resp.charName, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read charName: %w", err)
		return
	}
	unk3Len, err := in.Uint16()
	if err != nil {
		err = fmt.Errorf("read unk3.len: %w", err)
		return
	}
	resp.unk3, err = in.Bytes(unk3Len)
	if err != nil {
		err = fmt.Errorf("read unk3: %w", err)
		return
	}
	return
}
func UnmarshalAccountLogin(in *GwPacket.In) (resp AccountLogin, err error) {
	if in.Opcode() != 0x4 {
		err = errors.New("bad opcode")
		return
	}
	resp.reqNumber, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read reqNumber: %w", err)
		return
	}
	resp.salt, err = in.Bytes(4)
	if err != nil {
		err = fmt.Errorf("read salt: %w", err)
		return
	}
	resp.passwordHash, err = in.Bytes(20)
	if err != nil {
		err = fmt.Errorf("read passwordHash: %w", err)
		return
	}
	resp.email, err = in.UTF16WithLengthPrefix()
	if err != nil {
		err = fmt.Errorf("read email: %w", err)
		return
	}
	resp.unk2, err = in.Uint16()
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	return
}
func UnmarshalUnknown000f(in *GwPacket.In) (resp Unknown000f, err error) {
	if in.Opcode() != 0xf {
		err = errors.New("bad opcode")
		return
	}
	unk1Len, err := in.Uint16()
	if err != nil {
		err = fmt.Errorf("read unk1.len: %w", err)
		return
	}
	resp.unk1, err = in.Bytes(unk1Len)
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	resp.unk2, err = in.Bytes(16)
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	return
}
func UnmarshalUnknown0035(in *GwPacket.In) (resp Unknown0035, err error) {
	if in.Opcode() != 0x35 {
		err = errors.New("bad opcode")
		return
	}
	resp.reqNumber, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read reqNumber: %w", err)
		return
	}
	return
}
func UnmarshalUnknown000e(in *GwPacket.In) (resp Unknown000e, err error) {
	if in.Opcode() != 0xe {
		err = errors.New("bad opcode")
		return
	}
	resp.unk, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk: %w", err)
		return
	}
	return
}
func UnmarshalUnknown0029(in *GwPacket.In) (resp Unknown0029, err error) {
	if in.Opcode() != 0x29 {
		err = errors.New("bad opcode")
		return
	}
	resp.unk1, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk1: %w", err)
		return
	}
	resp.unk2, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk2: %w", err)
		return
	}
	resp.mapId, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read mapId: %w", err)
		return
	}
	resp.unk4, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk4: %w", err)
		return
	}
	resp.unk5, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk5: %w", err)
		return
	}
	resp.unk6, err = in.Uint32()
	if err != nil {
		err = fmt.Errorf("read unk6: %w", err)
		return
	}
	return
}
