// Code generated by go:generate; DO NOT EDIT.

package AuthService

import (
	"fmt"

	GwPacket "gw1/server/gwpacket"
)

func MarshalRequestResponse(reqNumber int, responseCode int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x3)
	resp.Uint32(reqNumber)
	resp.Uint32(responseCode)
	return
}

func MarshalCharacterSummary(reqNumber int, charUUID []byte, unk1 int, charName string, summary VarByte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x7)
	resp.Uint32(reqNumber)
	if len(charUUID) != 16 {
		panic(fmt.Errorf("length check failed for field 'charUUID' of struct 'CharacterSummary': %d vs %d", len(charUUID), 16))
	}
	resp.Bytes(charUUID)
	resp.Uint32(unk1)
	resp.UTF16WithLengthPrefix(charName)
	resp.Uint16(len(summary))
	resp.Bytes(summary)
	return
}

func MarshalAccountExtraInfoStart(reqNumber int, unk1 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x14)
	resp.Uint32(reqNumber)
	resp.Uint32(unk1)
	return
}

func MarshalAccountExtraInfo(reqNumber int, territoryCode int, languageCode int, unk1 []byte, unk2 []byte, accountUUID []byte, activeCharUUID []byte, unk3 int, entitlements VarByte, eulaByte int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x11)
	resp.Uint32(reqNumber)
	resp.Uint32(territoryCode)
	resp.Uint32(languageCode)
	if len(unk1) != 8 {
		panic(fmt.Errorf("length check failed for field 'unk1' of struct 'AccountExtraInfo': %d vs %d", len(unk1), 8))
	}
	resp.Bytes(unk1)
	if len(unk2) != 8 {
		panic(fmt.Errorf("length check failed for field 'unk2' of struct 'AccountExtraInfo': %d vs %d", len(unk2), 8))
	}
	resp.Bytes(unk2)
	if len(accountUUID) != 16 {
		panic(fmt.Errorf("length check failed for field 'accountUUID' of struct 'AccountExtraInfo': %d vs %d", len(accountUUID), 16))
	}
	resp.Bytes(accountUUID)
	if len(activeCharUUID) != 16 {
		panic(fmt.Errorf("length check failed for field 'activeCharUUID' of struct 'AccountExtraInfo': %d vs %d", len(activeCharUUID), 16))
	}
	resp.Bytes(activeCharUUID)
	resp.Uint32(unk3)
	resp.Uint16(len(entitlements))
	resp.Bytes(entitlements)
	resp.Uint8(eulaByte)
	return
}

func MarshalAccountBinaryInfo(reqNumber int, binaryData VarByte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x16)
	resp.Uint32(reqNumber)
	resp.Uint16(len(binaryData))
	resp.Bytes(binaryData)
	return
}

func MarshalServerSeed(xoredRandomBytes []byte) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1601)
	if len(xoredRandomBytes) != 20 {
		panic(fmt.Errorf("length check failed for field 'xoredRandomBytes' of struct 'ServerSeed': %d vs %d", len(xoredRandomBytes), 20))
	}
	resp.Bytes(xoredRandomBytes)
	return
}

func MarshalSessionSaltInfo(salt int, unk1 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x1)
	resp.Uint32(salt)
	resp.Uint32(unk1)
	return
}

func MarshalInstanceServerInfo(reqNumber int, worldHash int, mapId int, socketData []byte, playerHash int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x9)
	resp.Uint32(reqNumber)
	resp.Uint32(worldHash)
	resp.Uint32(mapId)
	if len(socketData) != 24 {
		panic(fmt.Errorf("length check failed for field 'socketData' of struct 'InstanceServerInfo': %d vs %d", len(socketData), 24))
	}
	resp.Bytes(socketData)
	resp.Uint32(playerHash)
	return
}

func MarshalUnknown0000(unk1 int, unk2 int) (resp GwPacket.Out) {
	resp = GwPacket.NewOut(0x0)
	resp.Uint32(unk1)
	resp.Uint32(unk2)
	return
}
